// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// UserType is an object representing the database table.
type UserType struct {
	Code    string `boil:"code" json:"code" toml:"code" yaml:"code"`
	Name    string `boil:"name" json:"name" toml:"name" yaml:"name"`
	IsAdmin bool   `boil:"is_admin" json:"is_admin" toml:"is_admin" yaml:"is_admin"`

	R *userTypeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userTypeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserTypeColumns = struct {
	Code    string
	Name    string
	IsAdmin string
}{
	Code:    "code",
	Name:    "name",
	IsAdmin: "is_admin",
}

var UserTypeTableColumns = struct {
	Code    string
	Name    string
	IsAdmin string
}{
	Code:    "user_type.code",
	Name:    "user_type.name",
	IsAdmin: "user_type.is_admin",
}

// Generated where

var UserTypeWhere = struct {
	Code    whereHelperstring
	Name    whereHelperstring
	IsAdmin whereHelperbool
}{
	Code:    whereHelperstring{field: "\"user_type\".\"code\""},
	Name:    whereHelperstring{field: "\"user_type\".\"name\""},
	IsAdmin: whereHelperbool{field: "\"user_type\".\"is_admin\""},
}

// UserTypeRels is where relationship names are stored.
var UserTypeRels = struct {
	Users string
}{
	Users: "Users",
}

// userTypeR is where relationships are stored.
type userTypeR struct {
	Users UserSlice `boil:"Users" json:"Users" toml:"Users" yaml:"Users"`
}

// NewStruct creates a new relationship struct
func (*userTypeR) NewStruct() *userTypeR {
	return &userTypeR{}
}

func (o *UserType) GetUsers() UserSlice {
	if o == nil {
		return nil
	}

	return o.R.GetUsers()
}

func (r *userTypeR) GetUsers() UserSlice {
	if r == nil {
		return nil
	}

	return r.Users
}

// userTypeL is where Load methods for each relationship are stored.
type userTypeL struct{}

var (
	userTypeAllColumns            = []string{"code", "name", "is_admin"}
	userTypeColumnsWithoutDefault = []string{"code", "name"}
	userTypeColumnsWithDefault    = []string{"is_admin"}
	userTypePrimaryKeyColumns     = []string{"code"}
	userTypeGeneratedColumns      = []string{}
)

type (
	// UserTypeSlice is an alias for a slice of pointers to UserType.
	// This should almost always be used instead of []UserType.
	UserTypeSlice []*UserType
	// UserTypeHook is the signature for custom UserType hook methods
	UserTypeHook func(context.Context, boil.ContextExecutor, *UserType) error

	userTypeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userTypeType                 = reflect.TypeOf(&UserType{})
	userTypeMapping              = queries.MakeStructMapping(userTypeType)
	userTypePrimaryKeyMapping, _ = queries.BindMapping(userTypeType, userTypeMapping, userTypePrimaryKeyColumns)
	userTypeInsertCacheMut       sync.RWMutex
	userTypeInsertCache          = make(map[string]insertCache)
	userTypeUpdateCacheMut       sync.RWMutex
	userTypeUpdateCache          = make(map[string]updateCache)
	userTypeUpsertCacheMut       sync.RWMutex
	userTypeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userTypeAfterSelectMu sync.Mutex
var userTypeAfterSelectHooks []UserTypeHook

var userTypeBeforeInsertMu sync.Mutex
var userTypeBeforeInsertHooks []UserTypeHook
var userTypeAfterInsertMu sync.Mutex
var userTypeAfterInsertHooks []UserTypeHook

var userTypeBeforeUpdateMu sync.Mutex
var userTypeBeforeUpdateHooks []UserTypeHook
var userTypeAfterUpdateMu sync.Mutex
var userTypeAfterUpdateHooks []UserTypeHook

var userTypeBeforeDeleteMu sync.Mutex
var userTypeBeforeDeleteHooks []UserTypeHook
var userTypeAfterDeleteMu sync.Mutex
var userTypeAfterDeleteHooks []UserTypeHook

var userTypeBeforeUpsertMu sync.Mutex
var userTypeBeforeUpsertHooks []UserTypeHook
var userTypeAfterUpsertMu sync.Mutex
var userTypeAfterUpsertHooks []UserTypeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserType) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userTypeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserType) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userTypeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserType) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userTypeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserType) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userTypeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserType) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userTypeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserType) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userTypeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserType) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userTypeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserType) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userTypeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserType) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userTypeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserTypeHook registers your hook function for all future operations.
func AddUserTypeHook(hookPoint boil.HookPoint, userTypeHook UserTypeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userTypeAfterSelectMu.Lock()
		userTypeAfterSelectHooks = append(userTypeAfterSelectHooks, userTypeHook)
		userTypeAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		userTypeBeforeInsertMu.Lock()
		userTypeBeforeInsertHooks = append(userTypeBeforeInsertHooks, userTypeHook)
		userTypeBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		userTypeAfterInsertMu.Lock()
		userTypeAfterInsertHooks = append(userTypeAfterInsertHooks, userTypeHook)
		userTypeAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		userTypeBeforeUpdateMu.Lock()
		userTypeBeforeUpdateHooks = append(userTypeBeforeUpdateHooks, userTypeHook)
		userTypeBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		userTypeAfterUpdateMu.Lock()
		userTypeAfterUpdateHooks = append(userTypeAfterUpdateHooks, userTypeHook)
		userTypeAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		userTypeBeforeDeleteMu.Lock()
		userTypeBeforeDeleteHooks = append(userTypeBeforeDeleteHooks, userTypeHook)
		userTypeBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		userTypeAfterDeleteMu.Lock()
		userTypeAfterDeleteHooks = append(userTypeAfterDeleteHooks, userTypeHook)
		userTypeAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		userTypeBeforeUpsertMu.Lock()
		userTypeBeforeUpsertHooks = append(userTypeBeforeUpsertHooks, userTypeHook)
		userTypeBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		userTypeAfterUpsertMu.Lock()
		userTypeAfterUpsertHooks = append(userTypeAfterUpsertHooks, userTypeHook)
		userTypeAfterUpsertMu.Unlock()
	}
}

// One returns a single userType record from the query.
func (q userTypeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserType, error) {
	o := &UserType{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: failed to execute a one query for user_type")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserType records from the query.
func (q userTypeQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserTypeSlice, error) {
	var o []*UserType

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to assign all query results to UserType slice")
	}

	if len(userTypeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserType records in the query.
func (q userTypeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to count user_type rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userTypeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "model: failed to check if user_type exists")
	}

	return count > 0, nil
}

// Users retrieves all the user's Users with an executor.
func (o *UserType) Users(mods ...qm.QueryMod) userQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"users\".\"user_type\"=?", o.Code),
	)

	return Users(queryMods...)
}

// LoadUsers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (userTypeL) LoadUsers(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserType any, mods queries.Applicator) error {
	var slice []*UserType
	var object *UserType

	if singular {
		var ok bool
		object, ok = maybeUserType.(*UserType)
		if !ok {
			object = new(UserType)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserType)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserType))
			}
		}
	} else {
		s, ok := maybeUserType.(*[]*UserType)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserType)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserType))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &userTypeR{}
		}
		args[object.Code] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userTypeR{}
			}
			args[obj.Code] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.user_type in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load users")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice users")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Users = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &userR{}
			}
			foreign.R.UserUserType = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Code == foreign.UserType {
				local.R.Users = append(local.R.Users, foreign)
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserUserType = local
				break
			}
		}
	}

	return nil
}

// AddUsers adds the given related objects to the existing relationships
// of the user_type, optionally inserting them as new records.
// Appends related to o.R.Users.
// Sets related.R.UserUserType appropriately.
func (o *UserType) AddUsers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*User) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.UserType = o.Code
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"users\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"user_type"}),
				strmangle.WhereClause("\"", "\"", 2, userPrimaryKeyColumns),
			)
			values := []any{o.Code, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.UserType = o.Code
		}
	}

	if o.R == nil {
		o.R = &userTypeR{
			Users: related,
		}
	} else {
		o.R.Users = append(o.R.Users, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &userR{
				UserUserType: o,
			}
		} else {
			rel.R.UserUserType = o
		}
	}
	return nil
}

// UserTypes retrieves all the records using an executor.
func UserTypes(mods ...qm.QueryMod) userTypeQuery {
	mods = append(mods, qm.From("\"user_type\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_type\".*"})
	}

	return userTypeQuery{q}
}

// FindUserType retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserType(ctx context.Context, exec boil.ContextExecutor, code string, selectCols ...string) (*UserType, error) {
	userTypeObj := &UserType{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_type\" where \"code\"=$1", sel,
	)

	q := queries.Raw(query, code)

	err := q.Bind(ctx, exec, userTypeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: unable to select from user_type")
	}

	if err = userTypeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userTypeObj, err
	}

	return userTypeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserType) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("model: no user_type provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userTypeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userTypeInsertCacheMut.RLock()
	cache, cached := userTypeInsertCache[key]
	userTypeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userTypeAllColumns,
			userTypeColumnsWithDefault,
			userTypeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userTypeType, userTypeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userTypeType, userTypeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_type\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_type\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "model: unable to insert into user_type")
	}

	if !cached {
		userTypeInsertCacheMut.Lock()
		userTypeInsertCache[key] = cache
		userTypeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserType.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserType) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userTypeUpdateCacheMut.RLock()
	cache, cached := userTypeUpdateCache[key]
	userTypeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userTypeAllColumns,
			userTypePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("model: unable to update user_type, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_type\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userTypePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userTypeType, userTypeMapping, append(wl, userTypePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update user_type row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by update for user_type")
	}

	if !cached {
		userTypeUpdateCacheMut.Lock()
		userTypeUpdateCache[key] = cache
		userTypeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userTypeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all for user_type")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected for user_type")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserTypeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("model: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userTypePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_type\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userTypePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all in userType slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected all in update all userType")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserType) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("model: no user_type provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userTypeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userTypeUpsertCacheMut.RLock()
	cache, cached := userTypeUpsertCache[key]
	userTypeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userTypeAllColumns,
			userTypeColumnsWithDefault,
			userTypeColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userTypeAllColumns,
			userTypePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("model: unable to upsert user_type, could not build update column list")
		}

		ret := strmangle.SetComplement(userTypeAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(userTypePrimaryKeyColumns) == 0 {
				return errors.New("model: unable to upsert user_type, could not build conflict column list")
			}

			conflict = make([]string, len(userTypePrimaryKeyColumns))
			copy(conflict, userTypePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_type\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(userTypeType, userTypeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userTypeType, userTypeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "model: unable to upsert user_type")
	}

	if !cached {
		userTypeUpsertCacheMut.Lock()
		userTypeUpsertCache[key] = cache
		userTypeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserType record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserType) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("model: no UserType provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userTypePrimaryKeyMapping)
	sql := "DELETE FROM \"user_type\" WHERE \"code\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete from user_type")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by delete for user_type")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userTypeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("model: no userTypeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from user_type")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for user_type")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserTypeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userTypeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userTypePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_type\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userTypePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from userType slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for user_type")
	}

	if len(userTypeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserType) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserType(ctx, exec, o.Code)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserTypeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserTypeSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userTypePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_type\".* FROM \"user_type\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userTypePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "model: unable to reload all in UserTypeSlice")
	}

	*o = slice

	return nil
}

// UserTypeExists checks if the UserType row exists.
func UserTypeExists(ctx context.Context, exec boil.ContextExecutor, code string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_type\" where \"code\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, code)
	}
	row := exec.QueryRowContext(ctx, sql, code)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "model: unable to check if user_type exists")
	}

	return exists, nil
}

// Exists checks if the UserType row exists.
func (o *UserType) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserTypeExists(ctx, exec, o.Code)
}
