// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q psql.Filterable]() struct {
	Companies companyWhere[Q]
	UserTypes userTypeWhere[Q]
	Users     userWhere[Q]
} {
	return struct {
		Companies companyWhere[Q]
		UserTypes userTypeWhere[Q]
		Users     userWhere[Q]
	}{
		Companies: buildCompanyWhere[Q](Companies.Columns),
		UserTypes: buildUserTypeWhere[Q](UserTypes.Columns),
		Users:     buildUserWhere[Q](Users.Columns),
	}
}
