// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Company is an object representing the database table.
type Company struct {
	ID        string           `db:"id,pk" `
	Name      string           `db:"name" `
	OwnerID   string           `db:"owner_id" `
	ManagerID null.Val[string] `db:"manager_id" `
	IsActive  bool             `db:"is_active" `
	LogoURL   null.Val[string] `db:"logo_url" `
	CreatedAt time.Time        `db:"created_at" `
	UpdatedAt time.Time        `db:"updated_at" `

	R companyR `db:"-" `
}

// CompanySlice is an alias for a slice of pointers to Company.
// This should almost always be used instead of []*Company.
type CompanySlice []*Company

// Companies contains methods to work with the companies table
var Companies = psql.NewTablex[*Company, CompanySlice, *CompanySetter]("", "companies", buildCompanyColumns("companies"))

// CompaniesQuery is a query on the companies table
type CompaniesQuery = *psql.ViewQuery[*Company, CompanySlice]

// companyR is where relationships are stored.
type companyR struct {
	ManagerUser *User // companies.companies_manager_id_fkey
	OwnerUser   *User // companies.companies_owner_id_fk
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded companyRLoaded `db:"-" `
}

// companyRLoaded tracks which relationships on Company have been loaded.
type companyRLoaded struct {
	ManagerUser bool // companies.companies_manager_id_fkey
	OwnerUser   bool // companies.companies_owner_id_fk
}

func buildCompanyColumns(tableName string) companyColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "name", "owner_id", "manager_id", "is_active", "logo_url", "created_at", "updated_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return companyColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildCompanyColumn(tableName, "id"),
		Name:        buildCompanyColumn(tableName, "name"),
		OwnerID:     buildCompanyColumn(tableName, "owner_id"),
		ManagerID:   buildCompanyColumn(tableName, "manager_id"),
		IsActive:    buildCompanyColumn(tableName, "is_active"),
		LogoURL:     buildCompanyColumn(tableName, "logo_url"),
		CreatedAt:   buildCompanyColumn(tableName, "created_at"),
		UpdatedAt:   buildCompanyColumn(tableName, "updated_at"),
	}
}

type companyColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         companyColumn
	Name       companyColumn
	OwnerID    companyColumn
	ManagerID  companyColumn
	IsActive   companyColumn
	LogoURL    companyColumn
	CreatedAt  companyColumn
	UpdatedAt  companyColumn
}

// Alias returns the current table alias for the columns set.
func (c companyColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (companyColumns) AliasedAs(tableName string) companyColumns {
	return buildCompanyColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c companyColumns) Unqualified() companyColumns {
	return buildCompanyColumns("")
}

func buildCompanyColumn(alias, name string) companyColumn {
	return companyColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type companyColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c companyColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c companyColumn) ShouldOmitParens() bool {
	return true
}

// CompanySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CompanySetter struct {
	ID        omit.Val[string]     `db:"id,pk" `
	Name      omit.Val[string]     `db:"name" `
	OwnerID   omit.Val[string]     `db:"owner_id" `
	ManagerID omitnull.Val[string] `db:"manager_id" `
	IsActive  omit.Val[bool]       `db:"is_active" `
	LogoURL   omitnull.Val[string] `db:"logo_url" `
	CreatedAt omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt omit.Val[time.Time]  `db:"updated_at" `
}

func (s CompanySetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.OwnerID.IsValue() {
		vals = append(vals, "owner_id")
	}
	if !s.ManagerID.IsUnset() {
		vals = append(vals, "manager_id")
	}
	if s.IsActive.IsValue() {
		vals = append(vals, "is_active")
	}
	if !s.LogoURL.IsUnset() {
		vals = append(vals, "logo_url")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s CompanySetter) Overwrite(t *Company) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.OwnerID.IsValue() {
		t.OwnerID = s.OwnerID.MustGet()
	}
	if !s.ManagerID.IsUnset() {
		t.ManagerID = s.ManagerID.MustGetNull()
	}
	if s.IsActive.IsValue() {
		t.IsActive = s.IsActive.MustGet()
	}
	if !s.LogoURL.IsUnset() {
		t.LogoURL = s.LogoURL.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *CompanySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Companies.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 8)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.OwnerID.IsValue() {
			vals[2] = psql.Arg(s.OwnerID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.ManagerID.IsUnset() {
			vals[3] = psql.Arg(s.ManagerID.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.IsActive.IsValue() {
			vals[4] = psql.Arg(s.IsActive.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.LogoURL.IsUnset() {
			vals[5] = psql.Arg(s.LogoURL.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[6] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[7] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s CompanySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s CompanySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.OwnerID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "owner_id")...),
			psql.Arg(s.OwnerID),
		}})
	}

	if !s.ManagerID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "manager_id")...),
			psql.Arg(s.ManagerID),
		}})
	}

	if s.IsActive.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_active")...),
			psql.Arg(s.IsActive),
		}})
	}

	if !s.LogoURL.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "logo_url")...),
			psql.Arg(s.LogoURL),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindCompany retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCompany(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Company, error) {
	if len(cols) == 0 {
		return Companies.Query(
			sm.Where(Companies.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Companies.Query(
		sm.Where(Companies.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Companies.Columns.Only(cols...)),
	).One(ctx, exec)
}

// CompanyExists checks the presence of a single record by primary key
func CompanyExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Companies.Query(
		sm.Where(Companies.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Company is retrieved from the database
func (o *Company) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Companies.AfterSelectHooks.RunHooks(ctx, exec, CompanySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Companies.AfterInsertHooks.RunHooks(ctx, exec, CompanySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Companies.AfterUpdateHooks.RunHooks(ctx, exec, CompanySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Companies.AfterDeleteHooks.RunHooks(ctx, exec, CompanySlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Companies.AfterMergeHooks.RunHooks(ctx, exec, CompanySlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Company
func (o *Company) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Company) pkEQ() dialect.Expression {
	return psql.Quote("companies", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Company
func (o *Company) Update(ctx context.Context, exec bob.Executor, s *CompanySetter) error {
	v, err := Companies.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Company record with an executor
func (o *Company) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Companies.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Company using the executor
func (o *Company) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Companies.Query(
		sm.Where(Companies.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after CompanySlice is retrieved from the database
func (o CompanySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Companies.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Companies.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Companies.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Companies.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Companies.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o CompanySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("companies", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CompanySlice) copyMatchingRows(from ...*Company) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CompanySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Companies.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Company:
				o.copyMatchingRows(retrieved)
			case []*Company:
				o.copyMatchingRows(retrieved...)
			case CompanySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Company or a slice of Company
				// then run the AfterUpdateHooks on the slice
				_, err = Companies.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CompanySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Companies.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Company:
				o.copyMatchingRows(retrieved)
			case []*Company:
				o.copyMatchingRows(retrieved...)
			case CompanySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Company or a slice of Company
				// then run the AfterDeleteHooks on the slice
				_, err = Companies.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o CompanySlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Companies.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Company:
				o.copyMatchingRows(retrieved)
			case []*Company:
				o.copyMatchingRows(retrieved...)
			case CompanySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Company or a slice of Company
				// then run the AfterMergeHooks on the slice
				_, err = Companies.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o CompanySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CompanySetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Companies.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o CompanySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Companies.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CompanySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Companies.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// ManagerUser starts a query for related objects on users
func (o *Company) ManagerUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.ManagerID))),
	)...)
}

func (os CompanySlice) ManagerUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkManagerID := make(pgtypes.Array[null.Val[string]], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkManagerID = append(pkManagerID, o.ManagerID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkManagerID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// OwnerUser starts a query for related objects on users
func (o *Company) OwnerUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.OwnerID))),
	)...)
}

func (os CompanySlice) OwnerUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkOwnerID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkOwnerID = append(pkOwnerID, o.OwnerID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkOwnerID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachCompanyManagerUser0(ctx context.Context, exec bob.Executor, count int, company0 *Company, user1 *User) (*Company, error) {
	setter := &CompanySetter{
		ManagerID: omitnull.From(user1.ID),
	}

	err := company0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCompanyManagerUser0: %w", err)
	}

	return company0, nil
}

func (company0 *Company) InsertManagerUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCompanyManagerUser0(ctx, exec, 1, company0, user1)
	if err != nil {
		return err
	}

	company0.R.ManagerUser = user1
	company0.R.Loaded.ManagerUser = true

	user1.R.ManagerCompanies = append(user1.R.ManagerCompanies, company0)

	return nil
}

func (company0 *Company) AttachManagerUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachCompanyManagerUser0(ctx, exec, 1, company0, user1)
	if err != nil {
		return err
	}

	company0.R.ManagerUser = user1
	company0.R.Loaded.ManagerUser = true

	user1.R.ManagerCompanies = append(user1.R.ManagerCompanies, company0)

	return nil
}

func attachCompanyOwnerUser0(ctx context.Context, exec bob.Executor, count int, company0 *Company, user1 *User) (*Company, error) {
	setter := &CompanySetter{
		OwnerID: omit.From(user1.ID),
	}

	err := company0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCompanyOwnerUser0: %w", err)
	}

	return company0, nil
}

func (company0 *Company) InsertOwnerUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCompanyOwnerUser0(ctx, exec, 1, company0, user1)
	if err != nil {
		return err
	}

	company0.R.OwnerUser = user1
	company0.R.Loaded.OwnerUser = true

	user1.R.OwnerCompanies = append(user1.R.OwnerCompanies, company0)

	return nil
}

func (company0 *Company) AttachOwnerUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachCompanyOwnerUser0(ctx, exec, 1, company0, user1)
	if err != nil {
		return err
	}

	company0.R.OwnerUser = user1
	company0.R.Loaded.OwnerUser = true

	user1.R.OwnerCompanies = append(user1.R.OwnerCompanies, company0)

	return nil
}

type companyWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, string]
	Name      psql.WhereMod[Q, string]
	OwnerID   psql.WhereMod[Q, string]
	ManagerID psql.WhereNullMod[Q, string]
	IsActive  psql.WhereMod[Q, bool]
	LogoURL   psql.WhereNullMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func (companyWhere[Q]) AliasedAs(alias string) companyWhere[Q] {
	return buildCompanyWhere[Q](buildCompanyColumns(alias))
}

func buildCompanyWhere[Q psql.Filterable](cols companyColumns) companyWhere[Q] {
	return companyWhere[Q]{
		ID:        psql.Where[Q, string](cols.ID.Expression),
		Name:      psql.Where[Q, string](cols.Name.Expression),
		OwnerID:   psql.Where[Q, string](cols.OwnerID.Expression),
		ManagerID: psql.WhereNull[Q, string](cols.ManagerID.Expression),
		IsActive:  psql.Where[Q, bool](cols.IsActive.Expression),
		LogoURL:   psql.WhereNull[Q, string](cols.LogoURL.Expression),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt.Expression),
	}
}

func (o *Company) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "ManagerUser":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("company cannot load %T as %q", retrieved, name)
		}

		o.R.ManagerUser = rel
		o.R.Loaded.ManagerUser = true

		if rel != nil {
			rel.R.ManagerCompanies = CompanySlice{o}
		}
		return nil
	case "OwnerUser":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("company cannot load %T as %q", retrieved, name)
		}

		o.R.OwnerUser = rel
		o.R.Loaded.OwnerUser = true

		if rel != nil {
			rel.R.OwnerCompanies = CompanySlice{o}
		}
		return nil
	default:
		return fmt.Errorf("company has no relationship %q", name)
	}
}

type companyPreloader struct {
	ManagerUser func(...psql.PreloadOption) psql.Preloader
	OwnerUser   func(...psql.PreloadOption) psql.Preloader
}

func buildCompanyPreloader() companyPreloader {
	return companyPreloader{
		ManagerUser: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "ManagerUser",
				Sides: []psql.PreloadSide{
					{
						From:        Companies,
						To:          Users,
						FromColumns: []string{"manager_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
		OwnerUser: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "OwnerUser",
				Sides: []psql.PreloadSide{
					{
						From:        Companies,
						To:          Users,
						FromColumns: []string{"owner_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type companyThenLoader[Q orm.Loadable] struct {
	ManagerUser func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	OwnerUser   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildCompanyThenLoader[Q orm.Loadable]() companyThenLoader[Q] {
	type ManagerUserLoadInterface interface {
		LoadManagerUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OwnerUserLoadInterface interface {
		LoadOwnerUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return companyThenLoader[Q]{
		ManagerUser: thenLoadBuilder[Q](
			"ManagerUser",
			func(ctx context.Context, exec bob.Executor, retrieved ManagerUserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadManagerUser(ctx, exec, mods...)
			},
		),
		OwnerUser: thenLoadBuilder[Q](
			"OwnerUser",
			func(ctx context.Context, exec bob.Executor, retrieved OwnerUserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOwnerUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadManagerUser loads the company's ManagerUser into the .R struct
func (o *Company) LoadManagerUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ManagerUser = nil
	o.R.Loaded.ManagerUser = false

	related, err := o.ManagerUser(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.ManagerCompanies = CompanySlice{o}

	o.R.ManagerUser = related
	o.R.Loaded.ManagerUser = true
	return nil
}

// LoadManagerUser loads the company's ManagerUser into the .R struct
func (os CompanySlice) LoadManagerUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.ManagerUser(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.ManagerUser = nil
		o.R.Loaded.ManagerUser = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {
			if !o.ManagerID.IsValue() {
				continue
			}

			if !(o.ManagerID.IsValue() && o.ManagerID.MustGet() == rel.ID) {
				continue
			}

			rel.R.ManagerCompanies = append(rel.R.ManagerCompanies, o)

			o.R.ManagerUser = rel
			break
		}
	}

	return nil
}

// LoadOwnerUser loads the company's OwnerUser into the .R struct
func (o *Company) LoadOwnerUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.OwnerUser = nil
	o.R.Loaded.OwnerUser = false

	related, err := o.OwnerUser(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.OwnerCompanies = CompanySlice{o}

	o.R.OwnerUser = related
	o.R.Loaded.OwnerUser = true
	return nil
}

// LoadOwnerUser loads the company's OwnerUser into the .R struct
func (os CompanySlice) LoadOwnerUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.OwnerUser(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.OwnerUser = nil
		o.R.Loaded.OwnerUser = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.OwnerID == rel.ID) {
				continue
			}

			rel.R.OwnerCompanies = append(rel.R.OwnerCompanies, o)

			o.R.OwnerUser = rel
			break
		}
	}

	return nil
}

type companyJoins[Q dialect.Joinable] struct {
	typ         string
	ManagerUser modAs[Q, userColumns]
	OwnerUser   modAs[Q, userColumns]
}

func (j companyJoins[Q]) aliasedAs(alias string) companyJoins[Q] {
	return buildCompanyJoins[Q](buildCompanyColumns(alias), j.typ)
}

func buildCompanyJoins[Q dialect.Joinable](cols companyColumns, typ string) companyJoins[Q] {
	return companyJoins[Q]{
		typ: typ,
		ManagerUser: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.ManagerID),
					))
				}

				return mods
			},
		},
		OwnerUser: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.OwnerID),
					))
				}

				return mods
			},
		},
	}
}
