// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// User is an object representing the database table.
type User struct {
	ID          string                    `db:"id,pk" `
	Name        string                    `db:"name" `
	Username    string                    `db:"username" `
	Password    string                    `db:"password" `
	PublicName  null.Val[string]          `db:"public_name" `
	Description null.Val[string]          `db:"description" `
	UserType    string                    `db:"user_type" `
	Age         int32                     `db:"age" `
	InitialAge  null.Val[int32]           `db:"initial_age" `
	Rate        float64                   `db:"rate" `
	LastRate    null.Val[float64]         `db:"last_rate" `
	IsActive    bool                      `db:"is_active" `
	ReadMessage null.Val[bool]            `db:"read_message" `
	Balance     decimal.Decimal           `db:"balance" `
	LockBalance null.Val[decimal.Decimal] `db:"lock_balance" `
	LastLogin   null.Val[time.Time]       `db:"last_login" `
	CreatedAt   time.Time                 `db:"created_at" `
	UpdatedAt   time.Time                 `db:"updated_at" `

	R userR `db:"-" `

	C userC `db:"-" `
}

// UserSlice is an alias for a slice of pointers to User.
// This should almost always be used instead of []*User.
type UserSlice []*User

// Users contains methods to work with the users table
var Users = psql.NewTablex[*User, UserSlice, *UserSetter]("", "users", buildUserColumns("users"))

// UsersQuery is a query on the users table
type UsersQuery = *psql.ViewQuery[*User, UserSlice]

// userR is where relationships are stored.
type userR struct {
	ManagerCompanies CompanySlice // companies.companies_manager_id_fkey
	OwnerCompanies   CompanySlice // companies.companies_owner_id_fk
	UserType         *UserType    // users.users_user_type_fkey
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded userRLoaded `db:"-" `
}

// userRLoaded tracks which relationships on User have been loaded.
type userRLoaded struct {
	ManagerCompanies bool // companies.companies_manager_id_fkey
	OwnerCompanies   bool // companies.companies_owner_id_fk
	UserType         bool // users.users_user_type_fkey
}

func buildUserColumns(tableName string) userColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "name", "username", "password", "public_name", "description", "user_type", "age", "initial_age", "rate", "last_rate", "is_active", "read_message", "balance", "lock_balance", "last_login", "created_at", "updated_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return userColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildUserColumn(tableName, "id"),
		Name:        buildUserColumn(tableName, "name"),
		Username:    buildUserColumn(tableName, "username"),
		Password:    buildUserColumn(tableName, "password"),
		PublicName:  buildUserColumn(tableName, "public_name"),
		Description: buildUserColumn(tableName, "description"),
		UserType:    buildUserColumn(tableName, "user_type"),
		Age:         buildUserColumn(tableName, "age"),
		InitialAge:  buildUserColumn(tableName, "initial_age"),
		Rate:        buildUserColumn(tableName, "rate"),
		LastRate:    buildUserColumn(tableName, "last_rate"),
		IsActive:    buildUserColumn(tableName, "is_active"),
		ReadMessage: buildUserColumn(tableName, "read_message"),
		Balance:     buildUserColumn(tableName, "balance"),
		LockBalance: buildUserColumn(tableName, "lock_balance"),
		LastLogin:   buildUserColumn(tableName, "last_login"),
		CreatedAt:   buildUserColumn(tableName, "created_at"),
		UpdatedAt:   buildUserColumn(tableName, "updated_at"),
	}
}

type userColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          userColumn
	Name        userColumn
	Username    userColumn
	Password    userColumn
	PublicName  userColumn
	Description userColumn
	UserType    userColumn
	Age         userColumn
	InitialAge  userColumn
	Rate        userColumn
	LastRate    userColumn
	IsActive    userColumn
	ReadMessage userColumn
	Balance     userColumn
	LockBalance userColumn
	LastLogin   userColumn
	CreatedAt   userColumn
	UpdatedAt   userColumn
}

// Alias returns the current table alias for the columns set.
func (c userColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (userColumns) AliasedAs(tableName string) userColumns {
	return buildUserColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c userColumns) Unqualified() userColumns {
	return buildUserColumns("")
}

func buildUserColumn(alias, name string) userColumn {
	return userColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type userColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c userColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c userColumn) ShouldOmitParens() bool {
	return true
}

// UserSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserSetter struct {
	ID          omit.Val[string]              `db:"id,pk" `
	Name        omit.Val[string]              `db:"name" `
	Username    omit.Val[string]              `db:"username" `
	Password    omit.Val[string]              `db:"password" `
	PublicName  omitnull.Val[string]          `db:"public_name" `
	Description omitnull.Val[string]          `db:"description" `
	UserType    omit.Val[string]              `db:"user_type" `
	Age         omit.Val[int32]               `db:"age" `
	InitialAge  omitnull.Val[int32]           `db:"initial_age" `
	Rate        omit.Val[float64]             `db:"rate" `
	LastRate    omitnull.Val[float64]         `db:"last_rate" `
	IsActive    omit.Val[bool]                `db:"is_active" `
	ReadMessage omitnull.Val[bool]            `db:"read_message" `
	Balance     omit.Val[decimal.Decimal]     `db:"balance" `
	LockBalance omitnull.Val[decimal.Decimal] `db:"lock_balance" `
	LastLogin   omitnull.Val[time.Time]       `db:"last_login" `
	CreatedAt   omit.Val[time.Time]           `db:"created_at" `
	UpdatedAt   omit.Val[time.Time]           `db:"updated_at" `
}

func (s UserSetter) SetColumns() []string {
	vals := make([]string, 0, 18)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Username.IsValue() {
		vals = append(vals, "username")
	}
	if s.Password.IsValue() {
		vals = append(vals, "password")
	}
	if !s.PublicName.IsUnset() {
		vals = append(vals, "public_name")
	}
	if !s.Description.IsUnset() {
		vals = append(vals, "description")
	}
	if s.UserType.IsValue() {
		vals = append(vals, "user_type")
	}
	if s.Age.IsValue() {
		vals = append(vals, "age")
	}
	if !s.InitialAge.IsUnset() {
		vals = append(vals, "initial_age")
	}
	if s.Rate.IsValue() {
		vals = append(vals, "rate")
	}
	if !s.LastRate.IsUnset() {
		vals = append(vals, "last_rate")
	}
	if s.IsActive.IsValue() {
		vals = append(vals, "is_active")
	}
	if !s.ReadMessage.IsUnset() {
		vals = append(vals, "read_message")
	}
	if s.Balance.IsValue() {
		vals = append(vals, "balance")
	}
	if !s.LockBalance.IsUnset() {
		vals = append(vals, "lock_balance")
	}
	if !s.LastLogin.IsUnset() {
		vals = append(vals, "last_login")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s UserSetter) Overwrite(t *User) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Username.IsValue() {
		t.Username = s.Username.MustGet()
	}
	if s.Password.IsValue() {
		t.Password = s.Password.MustGet()
	}
	if !s.PublicName.IsUnset() {
		t.PublicName = s.PublicName.MustGetNull()
	}
	if !s.Description.IsUnset() {
		t.Description = s.Description.MustGetNull()
	}
	if s.UserType.IsValue() {
		t.UserType = s.UserType.MustGet()
	}
	if s.Age.IsValue() {
		t.Age = s.Age.MustGet()
	}
	if !s.InitialAge.IsUnset() {
		t.InitialAge = s.InitialAge.MustGetNull()
	}
	if s.Rate.IsValue() {
		t.Rate = s.Rate.MustGet()
	}
	if !s.LastRate.IsUnset() {
		t.LastRate = s.LastRate.MustGetNull()
	}
	if s.IsActive.IsValue() {
		t.IsActive = s.IsActive.MustGet()
	}
	if !s.ReadMessage.IsUnset() {
		t.ReadMessage = s.ReadMessage.MustGetNull()
	}
	if s.Balance.IsValue() {
		t.Balance = s.Balance.MustGet()
	}
	if !s.LockBalance.IsUnset() {
		t.LockBalance = s.LockBalance.MustGetNull()
	}
	if !s.LastLogin.IsUnset() {
		t.LastLogin = s.LastLogin.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *UserSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Users.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 18)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Username.IsValue() {
			vals[2] = psql.Arg(s.Username.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Password.IsValue() {
			vals[3] = psql.Arg(s.Password.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.PublicName.IsUnset() {
			vals[4] = psql.Arg(s.PublicName.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.Description.IsUnset() {
			vals[5] = psql.Arg(s.Description.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.UserType.IsValue() {
			vals[6] = psql.Arg(s.UserType.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.Age.IsValue() {
			vals[7] = psql.Arg(s.Age.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if !s.InitialAge.IsUnset() {
			vals[8] = psql.Arg(s.InitialAge.MustGetNull())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if s.Rate.IsValue() {
			vals[9] = psql.Arg(s.Rate.MustGet())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if !s.LastRate.IsUnset() {
			vals[10] = psql.Arg(s.LastRate.MustGetNull())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		if s.IsActive.IsValue() {
			vals[11] = psql.Arg(s.IsActive.MustGet())
		} else {
			vals[11] = psql.Raw("DEFAULT")
		}

		if !s.ReadMessage.IsUnset() {
			vals[12] = psql.Arg(s.ReadMessage.MustGetNull())
		} else {
			vals[12] = psql.Raw("DEFAULT")
		}

		if s.Balance.IsValue() {
			vals[13] = psql.Arg(s.Balance.MustGet())
		} else {
			vals[13] = psql.Raw("DEFAULT")
		}

		if !s.LockBalance.IsUnset() {
			vals[14] = psql.Arg(s.LockBalance.MustGetNull())
		} else {
			vals[14] = psql.Raw("DEFAULT")
		}

		if !s.LastLogin.IsUnset() {
			vals[15] = psql.Arg(s.LastLogin.MustGetNull())
		} else {
			vals[15] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[16] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[16] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[17] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[17] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 18)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Username.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "username")...),
			psql.Arg(s.Username),
		}})
	}

	if s.Password.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "password")...),
			psql.Arg(s.Password),
		}})
	}

	if !s.PublicName.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "public_name")...),
			psql.Arg(s.PublicName),
		}})
	}

	if !s.Description.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	if s.UserType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_type")...),
			psql.Arg(s.UserType),
		}})
	}

	if s.Age.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "age")...),
			psql.Arg(s.Age),
		}})
	}

	if !s.InitialAge.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "initial_age")...),
			psql.Arg(s.InitialAge),
		}})
	}

	if s.Rate.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "rate")...),
			psql.Arg(s.Rate),
		}})
	}

	if !s.LastRate.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "last_rate")...),
			psql.Arg(s.LastRate),
		}})
	}

	if s.IsActive.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_active")...),
			psql.Arg(s.IsActive),
		}})
	}

	if !s.ReadMessage.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "read_message")...),
			psql.Arg(s.ReadMessage),
		}})
	}

	if s.Balance.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "balance")...),
			psql.Arg(s.Balance),
		}})
	}

	if !s.LockBalance.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lock_balance")...),
			psql.Arg(s.LockBalance),
		}})
	}

	if !s.LastLogin.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "last_login")...),
			psql.Arg(s.LastLogin),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindUser retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUser(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*User, error) {
	if len(cols) == 0 {
		return Users.Query(
			sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Users.Columns.Only(cols...)),
	).One(ctx, exec)
}

// UserExists checks the presence of a single record by primary key
func UserExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after User is retrieved from the database
func (o *User) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Users.AfterMergeHooks.RunHooks(ctx, exec, UserSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the User
func (o *User) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *User) pkEQ() dialect.Expression {
	return psql.Quote("users", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the User
func (o *User) Update(ctx context.Context, exec bob.Executor, s *UserSetter) error {
	v, err := Users.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single User record with an executor
func (o *User) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Users.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the User using the executor
func (o *User) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserSlice is retrieved from the database
func (o UserSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Users.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("users", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserSlice) copyMatchingRows(from ...*User) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterUpdateHooks on the slice
				_, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterDeleteHooks on the slice
				_, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o UserSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterMergeHooks on the slice
				_, err = Users.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o UserSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Users.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// ManagerCompanies starts a query for related objects on companies
func (o *User) ManagerCompanies(mods ...bob.Mod[*dialect.SelectQuery]) CompaniesQuery {
	return Companies.Query(append(mods,
		sm.Where(Companies.Columns.ManagerID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) ManagerCompanies(mods ...bob.Mod[*dialect.SelectQuery]) CompaniesQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Companies.Query(append(mods,
		sm.Where(psql.Group(Companies.Columns.ManagerID).OP("IN", PKArgExpr)),
	)...)
}

// OwnerCompanies starts a query for related objects on companies
func (o *User) OwnerCompanies(mods ...bob.Mod[*dialect.SelectQuery]) CompaniesQuery {
	return Companies.Query(append(mods,
		sm.Where(Companies.Columns.OwnerID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) OwnerCompanies(mods ...bob.Mod[*dialect.SelectQuery]) CompaniesQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Companies.Query(append(mods,
		sm.Where(psql.Group(Companies.Columns.OwnerID).OP("IN", PKArgExpr)),
	)...)
}

// UserType starts a query for related objects on user_type
func (o *User) RelatedUserType(mods ...bob.Mod[*dialect.SelectQuery]) UserTypesQuery {
	return UserTypes.Query(append(mods,
		sm.Where(UserTypes.Columns.Code.EQ(psql.Arg(o.UserType))),
	)...)
}

func (os UserSlice) RelatedUserType(mods ...bob.Mod[*dialect.SelectQuery]) UserTypesQuery {
	pkUserType := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserType = append(pkUserType, o.UserType)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserType), "character varying[]")),
	))

	return UserTypes.Query(append(mods,
		sm.Where(psql.Group(UserTypes.Columns.Code).OP("IN", PKArgExpr)),
	)...)
}

func insertUserManagerCompanies0(ctx context.Context, exec bob.Executor, companies1 []*CompanySetter, user0 *User) (CompanySlice, error) {
	for i := range companies1 {
		companies1[i].ManagerID = omitnull.From(user0.ID)
	}

	ret, err := Companies.Insert(bob.ToMods(companies1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserManagerCompanies0: %w", err)
	}

	return ret, nil
}

func attachUserManagerCompanies0(ctx context.Context, exec bob.Executor, count int, companies1 CompanySlice, user0 *User) (CompanySlice, error) {
	setter := &CompanySetter{
		ManagerID: omitnull.From(user0.ID),
	}

	err := companies1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserManagerCompanies0: %w", err)
	}

	return companies1, nil
}

func (user0 *User) InsertManagerCompanies(ctx context.Context, exec bob.Executor, related ...*CompanySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	companies1, err := insertUserManagerCompanies0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.ManagerCompanies = append(user0.R.ManagerCompanies, companies1...)

	for _, rel := range companies1 {
		rel.R.ManagerUser = user0
		rel.R.Loaded.ManagerUser = true
	}
	return nil
}

func (user0 *User) AttachManagerCompanies(ctx context.Context, exec bob.Executor, related ...*Company) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	companies1 := CompanySlice(related)

	_, err = attachUserManagerCompanies0(ctx, exec, len(related), companies1, user0)
	if err != nil {
		return err
	}

	user0.R.ManagerCompanies = append(user0.R.ManagerCompanies, companies1...)

	for _, rel := range related {
		rel.R.ManagerUser = user0
		rel.R.Loaded.ManagerUser = true
	}

	return nil
}

func insertUserOwnerCompanies0(ctx context.Context, exec bob.Executor, companies1 []*CompanySetter, user0 *User) (CompanySlice, error) {
	for i := range companies1 {
		companies1[i].OwnerID = omit.From(user0.ID)
	}

	ret, err := Companies.Insert(bob.ToMods(companies1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserOwnerCompanies0: %w", err)
	}

	return ret, nil
}

func attachUserOwnerCompanies0(ctx context.Context, exec bob.Executor, count int, companies1 CompanySlice, user0 *User) (CompanySlice, error) {
	setter := &CompanySetter{
		OwnerID: omit.From(user0.ID),
	}

	err := companies1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserOwnerCompanies0: %w", err)
	}

	return companies1, nil
}

func (user0 *User) InsertOwnerCompanies(ctx context.Context, exec bob.Executor, related ...*CompanySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	companies1, err := insertUserOwnerCompanies0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.OwnerCompanies = append(user0.R.OwnerCompanies, companies1...)

	for _, rel := range companies1 {
		rel.R.OwnerUser = user0
		rel.R.Loaded.OwnerUser = true
	}
	return nil
}

func (user0 *User) AttachOwnerCompanies(ctx context.Context, exec bob.Executor, related ...*Company) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	companies1 := CompanySlice(related)

	_, err = attachUserOwnerCompanies0(ctx, exec, len(related), companies1, user0)
	if err != nil {
		return err
	}

	user0.R.OwnerCompanies = append(user0.R.OwnerCompanies, companies1...)

	for _, rel := range related {
		rel.R.OwnerUser = user0
		rel.R.Loaded.OwnerUser = true
	}

	return nil
}

func attachUserUserType0(ctx context.Context, exec bob.Executor, count int, user0 *User, userType1 *UserType) (*User, error) {
	setter := &UserSetter{
		UserType: omit.From(userType1.Code),
	}

	err := user0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserUserType0: %w", err)
	}

	return user0, nil
}

func (user0 *User) InsertUserType(ctx context.Context, exec bob.Executor, related *UserTypeSetter) error {
	var err error

	userType1, err := UserTypes.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUserUserType0(ctx, exec, 1, user0, userType1)
	if err != nil {
		return err
	}

	user0.R.UserType = userType1
	user0.R.Loaded.UserType = true

	userType1.R.Users = append(userType1.R.Users, user0)

	return nil
}

func (user0 *User) AttachUserType(ctx context.Context, exec bob.Executor, userType1 *UserType) error {
	var err error

	_, err = attachUserUserType0(ctx, exec, 1, user0, userType1)
	if err != nil {
		return err
	}

	user0.R.UserType = userType1
	user0.R.Loaded.UserType = true

	userType1.R.Users = append(userType1.R.Users, user0)

	return nil
}

type userWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, string]
	Name        psql.WhereMod[Q, string]
	Username    psql.WhereMod[Q, string]
	Password    psql.WhereMod[Q, string]
	PublicName  psql.WhereNullMod[Q, string]
	Description psql.WhereNullMod[Q, string]
	UserType    psql.WhereMod[Q, string]
	Age         psql.WhereMod[Q, int32]
	InitialAge  psql.WhereNullMod[Q, int32]
	Rate        psql.WhereMod[Q, float64]
	LastRate    psql.WhereNullMod[Q, float64]
	IsActive    psql.WhereMod[Q, bool]
	ReadMessage psql.WhereNullMod[Q, bool]
	Balance     psql.WhereMod[Q, decimal.Decimal]
	LockBalance psql.WhereNullMod[Q, decimal.Decimal]
	LastLogin   psql.WhereNullMod[Q, time.Time]
	CreatedAt   psql.WhereMod[Q, time.Time]
	UpdatedAt   psql.WhereMod[Q, time.Time]
}

func (userWhere[Q]) AliasedAs(alias string) userWhere[Q] {
	return buildUserWhere[Q](buildUserColumns(alias))
}

func buildUserWhere[Q psql.Filterable](cols userColumns) userWhere[Q] {
	return userWhere[Q]{
		ID:          psql.Where[Q, string](cols.ID.Expression),
		Name:        psql.Where[Q, string](cols.Name.Expression),
		Username:    psql.Where[Q, string](cols.Username.Expression),
		Password:    psql.Where[Q, string](cols.Password.Expression),
		PublicName:  psql.WhereNull[Q, string](cols.PublicName.Expression),
		Description: psql.WhereNull[Q, string](cols.Description.Expression),
		UserType:    psql.Where[Q, string](cols.UserType.Expression),
		Age:         psql.Where[Q, int32](cols.Age.Expression),
		InitialAge:  psql.WhereNull[Q, int32](cols.InitialAge.Expression),
		Rate:        psql.Where[Q, float64](cols.Rate.Expression),
		LastRate:    psql.WhereNull[Q, float64](cols.LastRate.Expression),
		IsActive:    psql.Where[Q, bool](cols.IsActive.Expression),
		ReadMessage: psql.WhereNull[Q, bool](cols.ReadMessage.Expression),
		Balance:     psql.Where[Q, decimal.Decimal](cols.Balance.Expression),
		LockBalance: psql.WhereNull[Q, decimal.Decimal](cols.LockBalance.Expression),
		LastLogin:   psql.WhereNull[Q, time.Time](cols.LastLogin.Expression),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt:   psql.Where[Q, time.Time](cols.UpdatedAt.Expression),
	}
}

func (o *User) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "ManagerCompanies":
		rels, ok := retrieved.(CompanySlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.ManagerCompanies = rels
		o.R.Loaded.ManagerCompanies = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.ManagerUser = o
				rel.R.Loaded.ManagerUser = true
			}
		}
		return nil
	case "OwnerCompanies":
		rels, ok := retrieved.(CompanySlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.OwnerCompanies = rels
		o.R.Loaded.OwnerCompanies = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.OwnerUser = o
				rel.R.Loaded.OwnerUser = true
			}
		}
		return nil
	case "UserType":
		rel, ok := retrieved.(*UserType)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.UserType = rel
		o.R.Loaded.UserType = true

		if rel != nil {
			rel.R.Users = UserSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("user has no relationship %q", name)
	}
}

type userPreloader struct {
	UserType func(...psql.PreloadOption) psql.Preloader
}

func buildUserPreloader() userPreloader {
	return userPreloader{
		UserType: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*UserType, UserTypeSlice](psql.PreloadRel{
				Name: "UserType",
				Sides: []psql.PreloadSide{
					{
						From:        Users,
						To:          UserTypes,
						FromColumns: []string{"user_type"},
						ToColumns:   []string{"code"},
					},
				},
			}, UserTypes.Columns.Names(), opts...)
		},
	}
}

type userThenLoader[Q orm.Loadable] struct {
	ManagerCompanies func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	OwnerCompanies   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UserType         func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserThenLoader[Q orm.Loadable]() userThenLoader[Q] {
	type ManagerCompaniesLoadInterface interface {
		LoadManagerCompanies(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OwnerCompaniesLoadInterface interface {
		LoadOwnerCompanies(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserTypeLoadInterface interface {
		LoadUserType(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userThenLoader[Q]{
		ManagerCompanies: thenLoadBuilder[Q](
			"ManagerCompanies",
			func(ctx context.Context, exec bob.Executor, retrieved ManagerCompaniesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadManagerCompanies(ctx, exec, mods...)
			},
		),
		OwnerCompanies: thenLoadBuilder[Q](
			"OwnerCompanies",
			func(ctx context.Context, exec bob.Executor, retrieved OwnerCompaniesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOwnerCompanies(ctx, exec, mods...)
			},
		),
		UserType: thenLoadBuilder[Q](
			"UserType",
			func(ctx context.Context, exec bob.Executor, retrieved UserTypeLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUserType(ctx, exec, mods...)
			},
		),
	}
}

// LoadManagerCompanies loads the user's ManagerCompanies into the .R struct
func (o *User) LoadManagerCompanies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ManagerCompanies = nil
	o.R.Loaded.ManagerCompanies = false

	related, err := o.ManagerCompanies(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.ManagerUser = o
		rel.R.Loaded.ManagerUser = true
	}

	o.R.ManagerCompanies = related
	o.R.Loaded.ManagerCompanies = true
	return nil
}

// LoadManagerCompanies loads the user's ManagerCompanies into the .R struct
func (os UserSlice) LoadManagerCompanies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	companies, err := os.ManagerCompanies(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.ManagerCompanies = nil
		o.R.Loaded.ManagerCompanies = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range companies {

			if !rel.ManagerID.IsValue() {
				continue
			}
			if !(rel.ManagerID.IsValue() && o.ID == rel.ManagerID.MustGet()) {
				continue
			}

			rel.R.ManagerUser = o
			rel.R.Loaded.ManagerUser = true

			o.R.ManagerCompanies = append(o.R.ManagerCompanies, rel)
		}
	}

	return nil
}

// LoadOwnerCompanies loads the user's OwnerCompanies into the .R struct
func (o *User) LoadOwnerCompanies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.OwnerCompanies = nil
	o.R.Loaded.OwnerCompanies = false

	related, err := o.OwnerCompanies(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.OwnerUser = o
		rel.R.Loaded.OwnerUser = true
	}

	o.R.OwnerCompanies = related
	o.R.Loaded.OwnerCompanies = true
	return nil
}

// LoadOwnerCompanies loads the user's OwnerCompanies into the .R struct
func (os UserSlice) LoadOwnerCompanies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	companies, err := os.OwnerCompanies(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.OwnerCompanies = nil
		o.R.Loaded.OwnerCompanies = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range companies {

			if !(o.ID == rel.OwnerID) {
				continue
			}

			rel.R.OwnerUser = o
			rel.R.Loaded.OwnerUser = true

			o.R.OwnerCompanies = append(o.R.OwnerCompanies, rel)
		}
	}

	return nil
}

// LoadUserType loads the user's UserType into the .R struct
func (o *User) LoadUserType(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UserType = nil
	o.R.Loaded.UserType = false

	related, err := o.RelatedUserType(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Users = UserSlice{o}

	o.R.UserType = related
	o.R.Loaded.UserType = true
	return nil
}

// LoadUserType loads the user's UserType into the .R struct
func (os UserSlice) LoadUserType(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	userTypes, err := os.RelatedUserType(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.UserType = nil
		o.R.Loaded.UserType = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range userTypes {

			if !(o.UserType == rel.Code) {
				continue
			}

			rel.R.Users = append(rel.R.Users, o)

			o.R.UserType = rel
			break
		}
	}

	return nil
}

// userC is where relationship counts are stored.
type userC struct {
	ManagerCompanies *int64
	OwnerCompanies   *int64
}

// PreloadCount sets a count in the C struct by name
func (o *User) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "ManagerCompanies":
		o.C.ManagerCompanies = &count
	case "OwnerCompanies":
		o.C.OwnerCompanies = &count
	}
	return nil
}

type userCountPreloader struct {
	ManagerCompanies func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	OwnerCompanies   func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildUserCountPreloader() userCountPreloader {
	return userCountPreloader{
		ManagerCompanies: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*User]("ManagerCompanies", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Users.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Companies.Name()),
					sm.Where(psql.Quote(Companies.Alias(), "manager_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		OwnerCompanies: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*User]("OwnerCompanies", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Users.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Companies.Name()),
					sm.Where(psql.Quote(Companies.Alias(), "owner_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type userCountThenLoader[Q orm.Loadable] struct {
	ManagerCompanies func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	OwnerCompanies   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserCountThenLoader[Q orm.Loadable]() userCountThenLoader[Q] {
	type ManagerCompaniesCountInterface interface {
		LoadCountManagerCompanies(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OwnerCompaniesCountInterface interface {
		LoadCountOwnerCompanies(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userCountThenLoader[Q]{
		ManagerCompanies: countThenLoadBuilder[Q](
			"ManagerCompanies",
			func(ctx context.Context, exec bob.Executor, retrieved ManagerCompaniesCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountManagerCompanies(ctx, exec, mods...)
			},
		),
		OwnerCompanies: countThenLoadBuilder[Q](
			"OwnerCompanies",
			func(ctx context.Context, exec bob.Executor, retrieved OwnerCompaniesCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountOwnerCompanies(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountManagerCompanies loads the count of ManagerCompanies into the C struct
func (o *User) LoadCountManagerCompanies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.ManagerCompanies(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.ManagerCompanies = &count
	return nil
}

// LoadCountManagerCompanies loads the count of ManagerCompanies for a slice in a single batch query
func (os UserSlice) LoadCountManagerCompanies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Companies.Columns.ManagerID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Companies.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(Companies.Columns.ManagerID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Companies.Columns.ManagerID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.ManagerCompanies = &count
	}

	return nil
}

// LoadCountOwnerCompanies loads the count of OwnerCompanies into the C struct
func (o *User) LoadCountOwnerCompanies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.OwnerCompanies(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.OwnerCompanies = &count
	return nil
}

// LoadCountOwnerCompanies loads the count of OwnerCompanies for a slice in a single batch query
func (os UserSlice) LoadCountOwnerCompanies(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Companies.Columns.OwnerID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Companies.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(Companies.Columns.OwnerID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Companies.Columns.OwnerID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.OwnerCompanies = &count
	}

	return nil
}

type userJoins[Q dialect.Joinable] struct {
	typ              string
	ManagerCompanies modAs[Q, companyColumns]
	OwnerCompanies   modAs[Q, companyColumns]
	UserType         modAs[Q, userTypeColumns]
}

func (j userJoins[Q]) aliasedAs(alias string) userJoins[Q] {
	return buildUserJoins[Q](buildUserColumns(alias), j.typ)
}

func buildUserJoins[Q dialect.Joinable](cols userColumns, typ string) userJoins[Q] {
	return userJoins[Q]{
		typ: typ,
		ManagerCompanies: modAs[Q, companyColumns]{
			c: Companies.Columns,
			f: func(to companyColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Companies.Name().As(to.Alias())).On(
						to.ManagerID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		OwnerCompanies: modAs[Q, companyColumns]{
			c: Companies.Columns,
			f: func(to companyColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Companies.Name().As(to.Alias())).On(
						to.OwnerID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		UserType: modAs[Q, userTypeColumns]{
			c: UserTypes.Columns,
			f: func(to userTypeColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, UserTypes.Name().As(to.Alias())).On(
						to.Code.EQ(cols.UserType),
					))
				}

				return mods
			},
		},
	}
}
