// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// UserType is an object representing the database table.
type UserType struct {
	Code    string `db:"code,pk" `
	Name    string `db:"name" `
	IsAdmin bool   `db:"is_admin" `

	R userTypeR `db:"-" `

	C userTypeC `db:"-" `
}

// UserTypeSlice is an alias for a slice of pointers to UserType.
// This should almost always be used instead of []*UserType.
type UserTypeSlice []*UserType

// UserTypes contains methods to work with the user_type table
var UserTypes = psql.NewTablex[*UserType, UserTypeSlice, *UserTypeSetter]("", "user_type", buildUserTypeColumns("user_type"))

// UserTypesQuery is a query on the user_type table
type UserTypesQuery = *psql.ViewQuery[*UserType, UserTypeSlice]

// userTypeR is where relationships are stored.
type userTypeR struct {
	Users UserSlice // users.users_user_type_fkey
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded userTypeRLoaded `db:"-" `
}

// userTypeRLoaded tracks which relationships on UserType have been loaded.
type userTypeRLoaded struct {
	Users bool // users.users_user_type_fkey
}

func buildUserTypeColumns(tableName string) userTypeColumns {
	columnsExpr := expr.NewColumnsExpr(
		"code", "name", "is_admin",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return userTypeColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		Code:        buildUserTypeColumn(tableName, "code"),
		Name:        buildUserTypeColumn(tableName, "name"),
		IsAdmin:     buildUserTypeColumn(tableName, "is_admin"),
	}
}

type userTypeColumns struct {
	expr.ColumnsExpr
	tableAlias string
	Code       userTypeColumn
	Name       userTypeColumn
	IsAdmin    userTypeColumn
}

// Alias returns the current table alias for the columns set.
func (c userTypeColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (userTypeColumns) AliasedAs(tableName string) userTypeColumns {
	return buildUserTypeColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c userTypeColumns) Unqualified() userTypeColumns {
	return buildUserTypeColumns("")
}

func buildUserTypeColumn(alias, name string) userTypeColumn {
	return userTypeColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type userTypeColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c userTypeColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c userTypeColumn) ShouldOmitParens() bool {
	return true
}

// UserTypeSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserTypeSetter struct {
	Code    omit.Val[string] `db:"code,pk" `
	Name    omit.Val[string] `db:"name" `
	IsAdmin omit.Val[bool]   `db:"is_admin" `
}

func (s UserTypeSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.Code.IsValue() {
		vals = append(vals, "code")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.IsAdmin.IsValue() {
		vals = append(vals, "is_admin")
	}
	return vals
}

func (s UserTypeSetter) Overwrite(t *UserType) {
	if s.Code.IsValue() {
		t.Code = s.Code.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.IsAdmin.IsValue() {
		t.IsAdmin = s.IsAdmin.MustGet()
	}
}

func (s *UserTypeSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return UserTypes.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 3)
		if s.Code.IsValue() {
			vals[0] = psql.Arg(s.Code.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.IsAdmin.IsValue() {
			vals[2] = psql.Arg(s.IsAdmin.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserTypeSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserTypeSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.Code.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "code")...),
			psql.Arg(s.Code),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.IsAdmin.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_admin")...),
			psql.Arg(s.IsAdmin),
		}})
	}

	return exprs
}

// FindUserType retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUserType(ctx context.Context, exec bob.Executor, CodePK string, cols ...string) (*UserType, error) {
	if len(cols) == 0 {
		return UserTypes.Query(
			sm.Where(UserTypes.Columns.Code.EQ(psql.Arg(CodePK))),
		).One(ctx, exec)
	}

	return UserTypes.Query(
		sm.Where(UserTypes.Columns.Code.EQ(psql.Arg(CodePK))),
		sm.Columns(UserTypes.Columns.Only(cols...)),
	).One(ctx, exec)
}

// UserTypeExists checks the presence of a single record by primary key
func UserTypeExists(ctx context.Context, exec bob.Executor, CodePK string) (bool, error) {
	return UserTypes.Query(
		sm.Where(UserTypes.Columns.Code.EQ(psql.Arg(CodePK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after UserType is retrieved from the database
func (o *UserType) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UserTypes.AfterSelectHooks.RunHooks(ctx, exec, UserTypeSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = UserTypes.AfterInsertHooks.RunHooks(ctx, exec, UserTypeSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = UserTypes.AfterUpdateHooks.RunHooks(ctx, exec, UserTypeSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = UserTypes.AfterDeleteHooks.RunHooks(ctx, exec, UserTypeSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = UserTypes.AfterMergeHooks.RunHooks(ctx, exec, UserTypeSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the UserType
func (o *UserType) primaryKeyVals() bob.Expression {
	return psql.Arg(o.Code)
}

func (o *UserType) pkEQ() dialect.Expression {
	return psql.Quote("user_type", "code").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the UserType
func (o *UserType) Update(ctx context.Context, exec bob.Executor, s *UserTypeSetter) error {
	v, err := UserTypes.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single UserType record with an executor
func (o *UserType) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := UserTypes.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the UserType using the executor
func (o *UserType) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := UserTypes.Query(
		sm.Where(UserTypes.Columns.Code.EQ(psql.Arg(o.Code))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserTypeSlice is retrieved from the database
func (o UserTypeSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UserTypes.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = UserTypes.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = UserTypes.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = UserTypes.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = UserTypes.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserTypeSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("user_type", "code").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserTypeSlice) copyMatchingRows(from ...*UserType) {
	for i, old := range o {
		for _, new := range from {
			if new.Code != old.Code {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserTypeSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserTypes.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserType:
				o.copyMatchingRows(retrieved)
			case []*UserType:
				o.copyMatchingRows(retrieved...)
			case UserTypeSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserType or a slice of UserType
				// then run the AfterUpdateHooks on the slice
				_, err = UserTypes.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserTypeSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserTypes.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserType:
				o.copyMatchingRows(retrieved)
			case []*UserType:
				o.copyMatchingRows(retrieved...)
			case UserTypeSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserType or a slice of UserType
				// then run the AfterDeleteHooks on the slice
				_, err = UserTypes.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o UserTypeSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserTypes.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserType:
				o.copyMatchingRows(retrieved)
			case []*UserType:
				o.copyMatchingRows(retrieved...)
			case UserTypeSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserType or a slice of UserType
				// then run the AfterMergeHooks on the slice
				_, err = UserTypes.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o UserTypeSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserTypeSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UserTypes.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserTypeSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UserTypes.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserTypeSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := UserTypes.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Users starts a query for related objects on users
func (o *UserType) Users(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.UserType.EQ(psql.Arg(o.Code))),
	)...)
}

func (os UserTypeSlice) Users(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkCode := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkCode = append(pkCode, o.Code)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkCode), "character varying[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.UserType).OP("IN", PKArgExpr)),
	)...)
}

func insertUserTypeUsers0(ctx context.Context, exec bob.Executor, users1 []*UserSetter, userType0 *UserType) (UserSlice, error) {
	for i := range users1 {
		users1[i].UserType = omit.From(userType0.Code)
	}

	ret, err := Users.Insert(bob.ToMods(users1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserTypeUsers0: %w", err)
	}

	return ret, nil
}

func attachUserTypeUsers0(ctx context.Context, exec bob.Executor, count int, users1 UserSlice, userType0 *UserType) (UserSlice, error) {
	setter := &UserSetter{
		UserType: omit.From(userType0.Code),
	}

	err := users1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserTypeUsers0: %w", err)
	}

	return users1, nil
}

func (userType0 *UserType) InsertUsers(ctx context.Context, exec bob.Executor, related ...*UserSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	users1, err := insertUserTypeUsers0(ctx, exec, related, userType0)
	if err != nil {
		return err
	}

	userType0.R.Users = append(userType0.R.Users, users1...)

	for _, rel := range users1 {
		rel.R.UserType = userType0
		rel.R.Loaded.UserType = true
	}
	return nil
}

func (userType0 *UserType) AttachUsers(ctx context.Context, exec bob.Executor, related ...*User) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	users1 := UserSlice(related)

	_, err = attachUserTypeUsers0(ctx, exec, len(related), users1, userType0)
	if err != nil {
		return err
	}

	userType0.R.Users = append(userType0.R.Users, users1...)

	for _, rel := range related {
		rel.R.UserType = userType0
		rel.R.Loaded.UserType = true
	}

	return nil
}

type userTypeWhere[Q psql.Filterable] struct {
	Code    psql.WhereMod[Q, string]
	Name    psql.WhereMod[Q, string]
	IsAdmin psql.WhereMod[Q, bool]
}

func (userTypeWhere[Q]) AliasedAs(alias string) userTypeWhere[Q] {
	return buildUserTypeWhere[Q](buildUserTypeColumns(alias))
}

func buildUserTypeWhere[Q psql.Filterable](cols userTypeColumns) userTypeWhere[Q] {
	return userTypeWhere[Q]{
		Code:    psql.Where[Q, string](cols.Code.Expression),
		Name:    psql.Where[Q, string](cols.Name.Expression),
		IsAdmin: psql.Where[Q, bool](cols.IsAdmin.Expression),
	}
}

func (o *UserType) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Users":
		rels, ok := retrieved.(UserSlice)
		if !ok {
			return fmt.Errorf("userType cannot load %T as %q", retrieved, name)
		}

		o.R.Users = rels
		o.R.Loaded.Users = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.UserType = o
				rel.R.Loaded.UserType = true
			}
		}
		return nil
	default:
		return fmt.Errorf("userType has no relationship %q", name)
	}
}

type userTypePreloader struct{}

func buildUserTypePreloader() userTypePreloader {
	return userTypePreloader{}
}

type userTypeThenLoader[Q orm.Loadable] struct {
	Users func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserTypeThenLoader[Q orm.Loadable]() userTypeThenLoader[Q] {
	type UsersLoadInterface interface {
		LoadUsers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userTypeThenLoader[Q]{
		Users: thenLoadBuilder[Q](
			"Users",
			func(ctx context.Context, exec bob.Executor, retrieved UsersLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUsers(ctx, exec, mods...)
			},
		),
	}
}

// LoadUsers loads the userType's Users into the .R struct
func (o *UserType) LoadUsers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Users = nil
	o.R.Loaded.Users = false

	related, err := o.Users(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.UserType = o
		rel.R.Loaded.UserType = true
	}

	o.R.Users = related
	o.R.Loaded.Users = true
	return nil
}

// LoadUsers loads the userType's Users into the .R struct
func (os UserTypeSlice) LoadUsers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.Users(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Users = nil
		o.R.Loaded.Users = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.Code == rel.UserType) {
				continue
			}

			rel.R.UserType = o
			rel.R.Loaded.UserType = true

			o.R.Users = append(o.R.Users, rel)
		}
	}

	return nil
}

// userTypeC is where relationship counts are stored.
type userTypeC struct {
	Users *int64
}

// PreloadCount sets a count in the C struct by name
func (o *UserType) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Users":
		o.C.Users = &count
	}
	return nil
}

type userTypeCountPreloader struct {
	Users func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildUserTypeCountPreloader() userTypeCountPreloader {
	return userTypeCountPreloader{
		Users: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*UserType]("Users", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = UserTypes.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Users.Name()),
					sm.Where(psql.Quote(Users.Alias(), "user_type").EQ(psql.Quote(parent, "code"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type userTypeCountThenLoader[Q orm.Loadable] struct {
	Users func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserTypeCountThenLoader[Q orm.Loadable]() userTypeCountThenLoader[Q] {
	type UsersCountInterface interface {
		LoadCountUsers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userTypeCountThenLoader[Q]{
		Users: countThenLoadBuilder[Q](
			"Users",
			func(ctx context.Context, exec bob.Executor, retrieved UsersCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountUsers(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountUsers loads the count of Users into the C struct
func (o *UserType) LoadCountUsers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Users(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Users = &count
	return nil
}

// LoadCountUsers loads the count of Users for a slice in a single batch query
func (os UserTypeSlice) LoadCountUsers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkCode := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkCode = append(pkCode, o.Code)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkCode), "character varying[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		Code  string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Users.Columns.UserType.As("code"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Users.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(Users.Columns.UserType.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Users.Columns.UserType),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.Code] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.Code]
		o.C.Users = &count
	}

	return nil
}

type userTypeJoins[Q dialect.Joinable] struct {
	typ   string
	Users modAs[Q, userColumns]
}

func (j userTypeJoins[Q]) aliasedAs(alias string) userTypeJoins[Q] {
	return buildUserTypeJoins[Q](buildUserTypeColumns(alias), j.typ)
}

func buildUserTypeJoins[Q dialect.Joinable](cols userTypeColumns, typ string) userTypeJoins[Q] {
	return userTypeJoins[Q]{
		typ: typ,
		Users: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.UserType.EQ(cols.Code),
					))
				}

				return mods
			},
		},
	}
}
