// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var CompanyErrors = &companyErrors{
	ErrUniqueCompaniesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "companies",
		columns: []string{"id"},
		s:       "companies_pkey",
	},
}

type companyErrors struct {
	ErrUniqueCompaniesPkey *UniqueConstraintError
}
