// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var UserTypeErrors = &userTypeErrors{
	ErrUniqueUserTypePkey: &UniqueConstraintError{
		schema:  "",
		table:   "user_type",
		columns: []string{"code"},
		s:       "user_type_pkey",
	},
}

type userTypeErrors struct {
	ErrUniqueUserTypePkey *UniqueConstraintError
}
