// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var UserErrors = &userErrors{
	ErrUniqueUsersPkey: &UniqueConstraintError{
		schema:  "",
		table:   "users",
		columns: []string{"id"},
		s:       "users_pkey",
	},

	ErrUniqueUserUsernameUnique: &UniqueConstraintError{
		schema:  "",
		table:   "users",
		columns: []string{"username"},
		s:       "user_username_unique",
	},
}

type userErrors struct {
	ErrUniqueUsersPkey *UniqueConstraintError

	ErrUniqueUserUsernameUnique *UniqueConstraintError
}
