// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/grpc/proto/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneRequest) Reset() {
	*x = OneRequest{}
	mi := &file_pkg_grpc_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneRequest) ProtoMessage() {}

func (x *OneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneRequest.ProtoReflect.Descriptor instead.
func (*OneRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *OneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PublicName    string                 `protobuf:"bytes,4,opt,name=public_name,json=publicName,proto3" json:"public_name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Age           int64                  `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`
	InitialAge    int64                  `protobuf:"varint,7,opt,name=initial_age,json=initialAge,proto3" json:"initial_age,omitempty"`
	Rate          float64                `protobuf:"fixed64,8,opt,name=rate,proto3" json:"rate,omitempty"`
	LastRate      *float64               `protobuf:"fixed64,9,opt,name=last_rate,json=lastRate,proto3,oneof" json:"last_rate,omitempty"`
	IsActive      bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ReadMessage   *bool                  `protobuf:"varint,11,opt,name=read_message,json=readMessage,proto3,oneof" json:"read_message,omitempty"`
	Balance       float64                `protobuf:"fixed64,12,opt,name=balance,proto3" json:"balance,omitempty"`
	LockBalance   *float64               `protobuf:"fixed64,13,opt,name=lock_balance,json=lockBalance,proto3,oneof" json:"lock_balance,omitempty"`
	LastLogin     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_login,json=lastLogin,proto3,oneof" json:"last_login,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_pkg_grpc_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPublicName() string {
	if x != nil {
		return x.PublicName
	}
	return ""
}

func (x *User) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *User) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetInitialAge() int64 {
	if x != nil {
		return x.InitialAge
	}
	return 0
}

func (x *User) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *User) GetLastRate() float64 {
	if x != nil && x.LastRate != nil {
		return *x.LastRate
	}
	return 0
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetReadMessage() bool {
	if x != nil && x.ReadMessage != nil {
		return *x.ReadMessage
	}
	return false
}

func (x *User) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *User) GetLockBalance() float64 {
	if x != nil && x.LockBalance != nil {
		return *x.LockBalance
	}
	return 0
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_pkg_grpc_proto_user_proto protoreflect.FileDescriptor

const file_pkg_grpc_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/grpc/proto/user.proto\x12\aexample\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1c\n" +
	"\n" +
	"OneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xee\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1f\n" +
	"\vpublic_name\x18\x04 \x01(\tR\n" +
	"publicName\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x10\n" +
	"\x03age\x18\x06 \x01(\x03R\x03age\x12\x1f\n" +
	"\vinitial_age\x18\a \x01(\x03R\n" +
	"initialAge\x12\x12\n" +
	"\x04rate\x18\b \x01(\x01R\x04rate\x12 \n" +
	"\tlast_rate\x18\t \x01(\x01H\x00R\blastRate\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12&\n" +
	"\fread_message\x18\v \x01(\bH\x01R\vreadMessage\x88\x01\x01\x12\x18\n" +
	"\abalance\x18\f \x01(\x01R\abalance\x12&\n" +
	"\flock_balance\x18\r \x01(\x01H\x02R\vlockBalance\x88\x01\x01\x12>\n" +
	"\n" +
	"last_login\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\x03R\tlastLogin\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\f\n" +
	"\n" +
	"_last_rateB\x0f\n" +
	"\r_read_messageB\x0f\n" +
	"\r_lock_balanceB\r\n" +
	"\v_last_login28\n" +
	"\vUserService\x12)\n" +
	"\x03One\x12\x13.example.OneRequest\x1a\r.example.UserB6Z4github.com/stepanbukhtii/go-blueprint/pkg/grpc/protob\x06proto3"

var (
	file_pkg_grpc_proto_user_proto_rawDescOnce sync.Once
	file_pkg_grpc_proto_user_proto_rawDescData []byte
)

func file_pkg_grpc_proto_user_proto_rawDescGZIP() []byte {
	file_pkg_grpc_proto_user_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_user_proto_rawDesc), len(file_pkg_grpc_proto_user_proto_rawDesc)))
	})
	return file_pkg_grpc_proto_user_proto_rawDescData
}

var file_pkg_grpc_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_grpc_proto_user_proto_goTypes = []any{
	(*OneRequest)(nil),            // 0: example.OneRequest
	(*User)(nil),                  // 1: example.User
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pkg_grpc_proto_user_proto_depIdxs = []int32{
	2, // 0: example.User.last_login:type_name -> google.protobuf.Timestamp
	2, // 1: example.User.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: example.User.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: example.UserService.One:input_type -> example.OneRequest
	1, // 4: example.UserService.One:output_type -> example.User
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_grpc_proto_user_proto_init() }
func file_pkg_grpc_proto_user_proto_init() {
	if File_pkg_grpc_proto_user_proto != nil {
		return
	}
	file_pkg_grpc_proto_user_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_user_proto_rawDesc), len(file_pkg_grpc_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_proto_user_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_proto_user_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_proto_user_proto_msgTypes,
	}.Build()
	File_pkg_grpc_proto_user_proto = out.File
	file_pkg_grpc_proto_user_proto_goTypes = nil
	file_pkg_grpc_proto_user_proto_depIdxs = nil
}
