// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"
	"unsafe"

	"github.com/aarondl/opt/null"
	"github.com/shopspring/decimal"
	models "github.com/stepanbukhtii/go-blueprint/internal/repository/postgres/models"
)

type Factory struct {
	baseCompanyMods  CompanyModSlice
	baseUserTypeMods UserTypeModSlice
	baseUserMods     UserModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewCompany(mods ...CompanyMod) *CompanyTemplate {
	return f.NewCompanyWithContext(context.Background(), mods...)
}

func (f *Factory) NewCompanyWithContext(ctx context.Context, mods ...CompanyMod) *CompanyTemplate {
	o := &CompanyTemplate{f: f}

	if f != nil {
		f.baseCompanyMods.Apply(ctx, o)
	}

	CompanyModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingCompany(ctx context.Context, m *models.Company) *CompanyTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingCompany(ctx, m)
}

func (f *Factory) fromExistingCompany(ctx context.Context, m *models.Company) *CompanyTemplate {
	o := &CompanyTemplate{f: f, alreadyPersisted: true}

	o.ID = func() string { return m.ID }
	o.Name = func() string { return m.Name }
	o.OwnerID = func() string { return m.OwnerID }
	o.ManagerID = func() null.Val[string] { return m.ManagerID }
	o.IsActive = func() bool { return m.IsActive }
	o.LogoURL = func() null.Val[string] { return m.LogoURL }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if m.R.ManagerUser != nil {
		CompanyMods.WithExistingManagerUser(m.R.ManagerUser).Apply(ctx, o)
	}
	if m.R.OwnerUser != nil {
		CompanyMods.WithExistingOwnerUser(m.R.OwnerUser).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewUserType(mods ...UserTypeMod) *UserTypeTemplate {
	return f.NewUserTypeWithContext(context.Background(), mods...)
}

func (f *Factory) NewUserTypeWithContext(ctx context.Context, mods ...UserTypeMod) *UserTypeTemplate {
	o := &UserTypeTemplate{f: f}

	if f != nil {
		f.baseUserTypeMods.Apply(ctx, o)
	}

	UserTypeModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingUserType(ctx context.Context, m *models.UserType) *UserTypeTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingUserType(ctx, m)
}

func (f *Factory) fromExistingUserType(ctx context.Context, m *models.UserType) *UserTypeTemplate {
	o := &UserTypeTemplate{f: f, alreadyPersisted: true}

	o.Code = func() string { return m.Code }
	o.Name = func() string { return m.Name }
	o.IsAdmin = func() bool { return m.IsAdmin }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if len(m.R.Users) > 0 {
		UserTypeMods.AddExistingUsers(m.R.Users...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewUser(mods ...UserMod) *UserTemplate {
	return f.NewUserWithContext(context.Background(), mods...)
}

func (f *Factory) NewUserWithContext(ctx context.Context, mods ...UserMod) *UserTemplate {
	o := &UserTemplate{f: f}

	if f != nil {
		f.baseUserMods.Apply(ctx, o)
	}

	UserModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingUser(ctx context.Context, m *models.User) *UserTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingUser(ctx, m)
}

func (f *Factory) fromExistingUser(ctx context.Context, m *models.User) *UserTemplate {
	o := &UserTemplate{f: f, alreadyPersisted: true}

	o.ID = func() string { return m.ID }
	o.Name = func() string { return m.Name }
	o.Username = func() string { return m.Username }
	o.Password = func() string { return m.Password }
	o.PublicName = func() null.Val[string] { return m.PublicName }
	o.Description = func() null.Val[string] { return m.Description }
	o.UserType = func() string { return m.UserType }
	o.Age = func() int32 { return m.Age }
	o.InitialAge = func() null.Val[int32] { return m.InitialAge }
	o.Rate = func() float64 { return m.Rate }
	o.LastRate = func() null.Val[float64] { return m.LastRate }
	o.IsActive = func() bool { return m.IsActive }
	o.ReadMessage = func() null.Val[bool] { return m.ReadMessage }
	o.Balance = func() decimal.Decimal { return m.Balance }
	o.LockBalance = func() null.Val[decimal.Decimal] { return m.LockBalance }
	o.LastLogin = func() null.Val[time.Time] { return m.LastLogin }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if len(m.R.ManagerCompanies) > 0 {
		UserMods.AddExistingManagerCompanies(m.R.ManagerCompanies...).Apply(ctx, o)
	}
	if len(m.R.OwnerCompanies) > 0 {
		UserMods.AddExistingOwnerCompanies(m.R.OwnerCompanies...).Apply(ctx, o)
	}
	if m.R.UserType != nil {
		UserMods.WithExistingUserType(m.R.UserType).Apply(ctx, o)
	}

	return o
}

func (f *Factory) ClearBaseCompanyMods() {
	f.baseCompanyMods = nil
}

func (f *Factory) AddBaseCompanyMod(mods ...CompanyMod) {
	f.baseCompanyMods = append(f.baseCompanyMods, mods...)
}

func (f *Factory) ClearBaseUserTypeMods() {
	f.baseUserTypeMods = nil
}

func (f *Factory) AddBaseUserTypeMod(mods ...UserTypeMod) {
	f.baseUserTypeMods = append(f.baseUserTypeMods, mods...)
}

func (f *Factory) ClearBaseUserMods() {
	f.baseUserMods = nil
}

func (f *Factory) AddBaseUserMod(mods ...UserMod) {
	f.baseUserMods = append(f.baseUserMods, mods...)
}
