// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type contextKey string

var (
	factoryVisitedCtx = newContextual[map[uintptr]struct{}]("factoryVisited")

	// Relationship Contexts for companies
	companyWithParentsCascadingCtx = newContextual[bool]("companyWithParentsCascading")
	companyRelManagerUserCtx       = newContextual[bool]("companies.users.companies.companies_manager_id_fkey")
	companyRelOwnerUserCtx         = newContextual[bool]("companies.users.companies.companies_owner_id_fk")

	// Relationship Contexts for user_type
	userTypeWithParentsCascadingCtx = newContextual[bool]("userTypeWithParentsCascading")
	userTypeRelUsersCtx             = newContextual[bool]("user_type.users.users.users_user_type_fkey")

	// Relationship Contexts for users
	userWithParentsCascadingCtx = newContextual[bool]("userWithParentsCascading")
	userRelManagerCompaniesCtx  = newContextual[bool]("companies.users.companies.companies_manager_id_fkey")
	userRelOwnerCompaniesCtx    = newContextual[bool]("companies.users.companies.companies_owner_id_fk")
	userRelUserTypeCtx          = newContextual[bool]("user_type.users.users.users_user_type_fkey")

	modelsInCreationCtx = newContextual[map[string]any]("modelsInCreation")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
