// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/stepanbukhtii/go-blueprint/internal/repository/postgres/models"
	"github.com/stephenafamo/bob"
)

type CompanyMod interface {
	Apply(context.Context, *CompanyTemplate)
}

type CompanyModFunc func(context.Context, *CompanyTemplate)

func (f CompanyModFunc) Apply(ctx context.Context, n *CompanyTemplate) {
	f(ctx, n)
}

type CompanyModSlice []CompanyMod

func (mods CompanyModSlice) Apply(ctx context.Context, n *CompanyTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// CompanyTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type CompanyTemplate struct {
	ID        func() string
	Name      func() string
	OwnerID   func() string
	ManagerID func() null.Val[string]
	IsActive  func() bool
	LogoURL   func() null.Val[string]
	CreatedAt func() time.Time
	UpdatedAt func() time.Time

	r companyR
	f *Factory

	alreadyPersisted bool
}

type companyR struct {
	ManagerUser *companyRManagerUserR
	OwnerUser   *companyROwnerUserR
}

type companyRManagerUserR struct {
	o *UserTemplate
}
type companyROwnerUserR struct {
	o *UserTemplate
}

// Apply mods to the CompanyTemplate
func (o *CompanyTemplate) Apply(ctx context.Context, mods ...CompanyMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Company
// according to the relationships in the template. Nothing is inserted into the db
func (t CompanyTemplate) setModelRels(o *models.Company) {
	if t.r.ManagerUser != nil {
		rel := t.r.ManagerUser.o.Build()
		rel.R.ManagerCompanies = append(rel.R.ManagerCompanies, o)
		o.ManagerID = null.From(rel.ID) // h2
		o.R.ManagerUser = rel
		o.R.Loaded.ManagerUser = true
	}

	if t.r.OwnerUser != nil {
		rel := t.r.OwnerUser.o.Build()
		rel.R.OwnerCompanies = append(rel.R.OwnerCompanies, o)
		o.OwnerID = rel.ID // h2
		o.R.OwnerUser = rel
		o.R.Loaded.OwnerUser = true
	}
}

// BuildSetter returns an *models.CompanySetter
// this does nothing with the relationship templates
func (o CompanyTemplate) BuildSetter() *models.CompanySetter {
	m := &models.CompanySetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.OwnerID != nil {
		val := o.OwnerID()
		m.OwnerID = omit.From(val)
	}
	if o.ManagerID != nil {
		val := o.ManagerID()
		m.ManagerID = omitnull.FromNull(val)
	}
	if o.IsActive != nil {
		val := o.IsActive()
		m.IsActive = omit.From(val)
	}
	if o.LogoURL != nil {
		val := o.LogoURL()
		m.LogoURL = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.CompanySetter
// this does nothing with the relationship templates
func (o CompanyTemplate) BuildManySetter(number int) []*models.CompanySetter {
	m := make([]*models.CompanySetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Company
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CompanyTemplate.Create
func (o CompanyTemplate) Build() *models.Company {
	m := &models.Company{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.OwnerID != nil {
		m.OwnerID = o.OwnerID()
	}
	if o.ManagerID != nil {
		m.ManagerID = o.ManagerID()
	}
	if o.IsActive != nil {
		m.IsActive = o.IsActive()
	}
	if o.LogoURL != nil {
		m.LogoURL = o.LogoURL()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.CompanySlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CompanyTemplate.CreateMany
func (o CompanyTemplate) BuildMany(number int) models.CompanySlice {
	m := make(models.CompanySlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableCompany(m *models.CompanySetter) {
	if !(m.Name.IsValue()) {
		val := random_string(nil)
		m.Name = omit.From(val)
	}
	if !(m.OwnerID.IsValue()) {
		val := random_string(nil)
		m.OwnerID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Company
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *CompanyTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Company) error {
	var err error

	isManagerUserDone, _ := companyRelManagerUserCtx.Value(ctx)
	if !isManagerUserDone && o.r.ManagerUser != nil {
		ctx = companyRelManagerUserCtx.WithValue(ctx, true)
		if o.r.ManagerUser.o.alreadyPersisted {
			m.R.ManagerUser = o.r.ManagerUser.o.Build()
			m.R.Loaded.ManagerUser = true
		} else {
			var rel0 *models.User
			rel0, err = o.r.ManagerUser.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachManagerUser(ctx, exec, rel0)
			if err != nil {
				return err
			}
		}

	}

	return err
}

// Create builds a company and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *CompanyTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Company, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableCompany(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	var rel1 *models.User

	if o.r.OwnerUser == nil {
		if parentModel, found := mInCreation["users:companies:companies.companies_owner_id_fk"]; found {
			if pModel, ok := parentModel.(*models.User); ok {
				rel1 = pModel
			}
		}
	}

	if rel1 == nil {
		if o.r.OwnerUser == nil {
			CompanyMods.WithNewOwnerUser().Apply(ctx, o)
		}

		if o.r.OwnerUser.o.alreadyPersisted {
			rel1 = o.r.OwnerUser.o.Build()
		} else {
			rel1, err = o.r.OwnerUser.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.OwnerID = omit.From(rel1.ID)

	m, err := models.Companies.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	m.R.OwnerUser = rel1
	m.R.Loaded.OwnerUser = true

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a company and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *CompanyTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Company {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a company and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *CompanyTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Company {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple companies and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o CompanyTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.CompanySlice, error) {
	var err error
	m := make(models.CompanySlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple companies and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o CompanyTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.CompanySlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple companies and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o CompanyTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.CompanySlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Company has methods that act as mods for the CompanyTemplate
var CompanyMods companyMods

type companyMods struct{}

func (m companyMods) RandomizeAllColumns(f *faker.Faker) CompanyMod {
	return CompanyModSlice{
		CompanyMods.RandomID(f),
		CompanyMods.RandomName(f),
		CompanyMods.RandomOwnerID(f),
		CompanyMods.RandomManagerID(f),
		CompanyMods.RandomIsActive(f),
		CompanyMods.RandomLogoURL(f),
		CompanyMods.RandomCreatedAt(f),
		CompanyMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m companyMods) ID(val string) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m companyMods) IDFunc(f func() string) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m companyMods) UnsetID() CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m companyMods) RandomID(f *faker.Faker) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m companyMods) Name(val string) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m companyMods) NameFunc(f func() string) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m companyMods) UnsetName() CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m companyMods) RandomName(f *faker.Faker) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m companyMods) OwnerID(val string) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.OwnerID = func() string { return val }
	})
}

// Set the Column from the function
func (m companyMods) OwnerIDFunc(f func() string) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.OwnerID = f
	})
}

// Clear any values for the column
func (m companyMods) UnsetOwnerID() CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.OwnerID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m companyMods) RandomOwnerID(f *faker.Faker) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.OwnerID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m companyMods) ManagerID(val null.Val[string]) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.ManagerID = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m companyMods) ManagerIDFunc(f func() null.Val[string]) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.ManagerID = f
	})
}

// Clear any values for the column
func (m companyMods) UnsetManagerID() CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.ManagerID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m companyMods) RandomManagerID(f *faker.Faker) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.ManagerID = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m companyMods) RandomManagerIDNotNull(f *faker.Faker) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.ManagerID = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m companyMods) IsActive(val bool) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.IsActive = func() bool { return val }
	})
}

// Set the Column from the function
func (m companyMods) IsActiveFunc(f func() bool) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.IsActive = f
	})
}

// Clear any values for the column
func (m companyMods) UnsetIsActive() CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.IsActive = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m companyMods) RandomIsActive(f *faker.Faker) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.IsActive = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m companyMods) LogoURL(val null.Val[string]) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.LogoURL = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m companyMods) LogoURLFunc(f func() null.Val[string]) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.LogoURL = f
	})
}

// Clear any values for the column
func (m companyMods) UnsetLogoURL() CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.LogoURL = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m companyMods) RandomLogoURL(f *faker.Faker) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.LogoURL = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m companyMods) RandomLogoURLNotNull(f *faker.Faker) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.LogoURL = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m companyMods) CreatedAt(val time.Time) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m companyMods) CreatedAtFunc(f func() time.Time) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m companyMods) UnsetCreatedAt() CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m companyMods) RandomCreatedAt(f *faker.Faker) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m companyMods) UpdatedAt(val time.Time) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m companyMods) UpdatedAtFunc(f func() time.Time) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m companyMods) UnsetUpdatedAt() CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m companyMods) RandomUpdatedAt(f *faker.Faker) CompanyMod {
	return CompanyModFunc(func(_ context.Context, o *CompanyTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m companyMods) WithParentsCascading() CompanyMod {
	return CompanyModFunc(func(ctx context.Context, o *CompanyTemplate) {
		if isDone, _ := companyWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = companyWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithManagerUser(related).Apply(ctx, o)
		}
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithOwnerUser(related).Apply(ctx, o)
		}
	})
}

func (m companyMods) WithManagerUser(rel *UserTemplate) CompanyMod {
	return CompanyModFunc(func(ctx context.Context, o *CompanyTemplate) {
		o.r.ManagerUser = &companyRManagerUserR{
			o: rel,
		}
	})
}

func (m companyMods) WithNewManagerUser(mods ...UserMod) CompanyMod {
	return CompanyModFunc(func(ctx context.Context, o *CompanyTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithManagerUser(related).Apply(ctx, o)
	})
}

func (m companyMods) WithExistingManagerUser(em *models.User) CompanyMod {
	return CompanyModFunc(func(ctx context.Context, o *CompanyTemplate) {
		o.r.ManagerUser = &companyRManagerUserR{
			o: o.f.fromExistingUser(ctx, em),
		}
	})
}

func (m companyMods) WithoutManagerUser() CompanyMod {
	return CompanyModFunc(func(ctx context.Context, o *CompanyTemplate) {
		o.r.ManagerUser = nil
	})
}

func (m companyMods) WithOwnerUser(rel *UserTemplate) CompanyMod {
	return CompanyModFunc(func(ctx context.Context, o *CompanyTemplate) {
		o.r.OwnerUser = &companyROwnerUserR{
			o: rel,
		}
	})
}

func (m companyMods) WithNewOwnerUser(mods ...UserMod) CompanyMod {
	return CompanyModFunc(func(ctx context.Context, o *CompanyTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithOwnerUser(related).Apply(ctx, o)
	})
}

func (m companyMods) WithExistingOwnerUser(em *models.User) CompanyMod {
	return CompanyModFunc(func(ctx context.Context, o *CompanyTemplate) {
		o.r.OwnerUser = &companyROwnerUserR{
			o: o.f.fromExistingUser(ctx, em),
		}
	})
}

func (m companyMods) WithoutOwnerUser() CompanyMod {
	return CompanyModFunc(func(ctx context.Context, o *CompanyTemplate) {
		o.r.OwnerUser = nil
	})
}
