// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/shopspring/decimal"
	models "github.com/stepanbukhtii/go-blueprint/internal/repository/postgres/models"
	"github.com/stephenafamo/bob"
)

type UserMod interface {
	Apply(context.Context, *UserTemplate)
}

type UserModFunc func(context.Context, *UserTemplate)

func (f UserModFunc) Apply(ctx context.Context, n *UserTemplate) {
	f(ctx, n)
}

type UserModSlice []UserMod

func (mods UserModSlice) Apply(ctx context.Context, n *UserTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// UserTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type UserTemplate struct {
	ID          func() string
	Name        func() string
	Username    func() string
	Password    func() string
	PublicName  func() null.Val[string]
	Description func() null.Val[string]
	UserType    func() string
	Age         func() int32
	InitialAge  func() null.Val[int32]
	Rate        func() float64
	LastRate    func() null.Val[float64]
	IsActive    func() bool
	ReadMessage func() null.Val[bool]
	Balance     func() decimal.Decimal
	LockBalance func() null.Val[decimal.Decimal]
	LastLogin   func() null.Val[time.Time]
	CreatedAt   func() time.Time
	UpdatedAt   func() time.Time

	r userR
	f *Factory

	alreadyPersisted bool
}

type userR struct {
	ManagerCompanies []*userRManagerCompaniesR
	OwnerCompanies   []*userROwnerCompaniesR
	UserType         *userRUserTypeR
}

type userRManagerCompaniesR struct {
	number int
	o      *CompanyTemplate
}
type userROwnerCompaniesR struct {
	number int
	o      *CompanyTemplate
}
type userRUserTypeR struct {
	o *UserTypeTemplate
}

// Apply mods to the UserTemplate
func (o *UserTemplate) Apply(ctx context.Context, mods ...UserMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.User
// according to the relationships in the template. Nothing is inserted into the db
func (t UserTemplate) setModelRels(o *models.User) {
	if t.r.ManagerCompanies != nil {
		rel := models.CompanySlice{}
		for _, r := range t.r.ManagerCompanies {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ManagerID = null.From(o.ID) // h2
				rel.R.ManagerUser = o
				rel.R.Loaded.ManagerUser = true
			}
			rel = append(rel, related...)
		}
		o.R.ManagerCompanies = rel
		o.R.Loaded.ManagerCompanies = true
	}

	if t.r.OwnerCompanies != nil {
		rel := models.CompanySlice{}
		for _, r := range t.r.OwnerCompanies {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.OwnerID = o.ID // h2
				rel.R.OwnerUser = o
				rel.R.Loaded.OwnerUser = true
			}
			rel = append(rel, related...)
		}
		o.R.OwnerCompanies = rel
		o.R.Loaded.OwnerCompanies = true
	}

	if t.r.UserType != nil {
		rel := t.r.UserType.o.Build()
		rel.R.Users = append(rel.R.Users, o)
		o.UserType = rel.Code // h2
		o.R.UserType = rel
		o.R.Loaded.UserType = true
	}
}

// BuildSetter returns an *models.UserSetter
// this does nothing with the relationship templates
func (o UserTemplate) BuildSetter() *models.UserSetter {
	m := &models.UserSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.Username != nil {
		val := o.Username()
		m.Username = omit.From(val)
	}
	if o.Password != nil {
		val := o.Password()
		m.Password = omit.From(val)
	}
	if o.PublicName != nil {
		val := o.PublicName()
		m.PublicName = omitnull.FromNull(val)
	}
	if o.Description != nil {
		val := o.Description()
		m.Description = omitnull.FromNull(val)
	}
	if o.UserType != nil {
		val := o.UserType()
		m.UserType = omit.From(val)
	}
	if o.Age != nil {
		val := o.Age()
		m.Age = omit.From(val)
	}
	if o.InitialAge != nil {
		val := o.InitialAge()
		m.InitialAge = omitnull.FromNull(val)
	}
	if o.Rate != nil {
		val := o.Rate()
		m.Rate = omit.From(val)
	}
	if o.LastRate != nil {
		val := o.LastRate()
		m.LastRate = omitnull.FromNull(val)
	}
	if o.IsActive != nil {
		val := o.IsActive()
		m.IsActive = omit.From(val)
	}
	if o.ReadMessage != nil {
		val := o.ReadMessage()
		m.ReadMessage = omitnull.FromNull(val)
	}
	if o.Balance != nil {
		val := o.Balance()
		m.Balance = omit.From(val)
	}
	if o.LockBalance != nil {
		val := o.LockBalance()
		m.LockBalance = omitnull.FromNull(val)
	}
	if o.LastLogin != nil {
		val := o.LastLogin()
		m.LastLogin = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.UserSetter
// this does nothing with the relationship templates
func (o UserTemplate) BuildManySetter(number int) []*models.UserSetter {
	m := make([]*models.UserSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.User
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserTemplate.Create
func (o UserTemplate) Build() *models.User {
	m := &models.User{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Username != nil {
		m.Username = o.Username()
	}
	if o.Password != nil {
		m.Password = o.Password()
	}
	if o.PublicName != nil {
		m.PublicName = o.PublicName()
	}
	if o.Description != nil {
		m.Description = o.Description()
	}
	if o.UserType != nil {
		m.UserType = o.UserType()
	}
	if o.Age != nil {
		m.Age = o.Age()
	}
	if o.InitialAge != nil {
		m.InitialAge = o.InitialAge()
	}
	if o.Rate != nil {
		m.Rate = o.Rate()
	}
	if o.LastRate != nil {
		m.LastRate = o.LastRate()
	}
	if o.IsActive != nil {
		m.IsActive = o.IsActive()
	}
	if o.ReadMessage != nil {
		m.ReadMessage = o.ReadMessage()
	}
	if o.Balance != nil {
		m.Balance = o.Balance()
	}
	if o.LockBalance != nil {
		m.LockBalance = o.LockBalance()
	}
	if o.LastLogin != nil {
		m.LastLogin = o.LastLogin()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.UserSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserTemplate.CreateMany
func (o UserTemplate) BuildMany(number int) models.UserSlice {
	m := make(models.UserSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableUser(m *models.UserSetter) {
	if !(m.Name.IsValue()) {
		val := random_string(nil)
		m.Name = omit.From(val)
	}
	if !(m.Username.IsValue()) {
		val := random_string(nil)
		m.Username = omit.From(val)
	}
	if !(m.Password.IsValue()) {
		val := random_string(nil)
		m.Password = omit.From(val)
	}
	if !(m.UserType.IsValue()) {
		val := random_string(nil)
		m.UserType = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.User
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *UserTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.User) error {
	var err error

	isManagerCompaniesDone, _ := userRelManagerCompaniesCtx.Value(ctx)
	if !isManagerCompaniesDone && o.r.ManagerCompanies != nil {
		ctx = userRelManagerCompaniesCtx.WithValue(ctx, true)
		for _, r := range o.r.ManagerCompanies {
			if r.o.alreadyPersisted {
				m.R.ManagerCompanies = append(m.R.ManagerCompanies, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachManagerCompanies(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isOwnerCompaniesDone, _ := userRelOwnerCompaniesCtx.Value(ctx)
	if !isOwnerCompaniesDone && o.r.OwnerCompanies != nil {
		ctx = userRelOwnerCompaniesCtx.WithValue(ctx, true)
		for _, r := range o.r.OwnerCompanies {
			if r.o.alreadyPersisted {
				m.R.OwnerCompanies = append(m.R.OwnerCompanies, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOwnerCompanies(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *UserTemplate) Create(ctx context.Context, exec bob.Executor) (*models.User, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableUser(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	var rel2 *models.UserType

	if o.r.UserType == nil {
		if parentModel, found := mInCreation["user_type:users:users.users_user_type_fkey"]; found {
			if pModel, ok := parentModel.(*models.UserType); ok {
				rel2 = pModel
			}
		}
	}

	if rel2 == nil {
		if o.r.UserType == nil {
			UserMods.WithNewUserType().Apply(ctx, o)
		}

		if o.r.UserType.o.alreadyPersisted {
			rel2 = o.r.UserType.o.Build()
		} else {
			rel2, err = o.r.UserType.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.UserType = omit.From(rel2.Code)

	m, err := models.Users.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}
	newMInCreation["users:companies:companies.companies_manager_id_fkey"] = m
	newMInCreation["users:companies:companies.companies_owner_id_fk"] = m

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	m.R.UserType = rel2
	m.R.Loaded.UserType = true

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *UserTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.User {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *UserTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.User {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o UserTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.UserSlice, error) {
	var err error
	m := make(models.UserSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o UserTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.UserSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o UserTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.UserSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// User has methods that act as mods for the UserTemplate
var UserMods userMods

type userMods struct{}

func (m userMods) RandomizeAllColumns(f *faker.Faker) UserMod {
	return UserModSlice{
		UserMods.RandomID(f),
		UserMods.RandomName(f),
		UserMods.RandomUsername(f),
		UserMods.RandomPassword(f),
		UserMods.RandomPublicName(f),
		UserMods.RandomDescription(f),
		UserMods.RandomUserType(f),
		UserMods.RandomAge(f),
		UserMods.RandomInitialAge(f),
		UserMods.RandomRate(f),
		UserMods.RandomLastRate(f),
		UserMods.RandomIsActive(f),
		UserMods.RandomReadMessage(f),
		UserMods.RandomBalance(f),
		UserMods.RandomLockBalance(f),
		UserMods.RandomLastLogin(f),
		UserMods.RandomCreatedAt(f),
		UserMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m userMods) ID(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) IDFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m userMods) UnsetID() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomID(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) Name(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) NameFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m userMods) UnsetName() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomName(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) Username(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Username = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) UsernameFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Username = f
	})
}

// Clear any values for the column
func (m userMods) UnsetUsername() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Username = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomUsername(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Username = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) Password(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) PasswordFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = f
	})
}

// Clear any values for the column
func (m userMods) UnsetPassword() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomPassword(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Password = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) PublicName(val null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.PublicName = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m userMods) PublicNameFunc(f func() null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.PublicName = f
	})
}

// Clear any values for the column
func (m userMods) UnsetPublicName() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.PublicName = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomPublicName(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.PublicName = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomPublicNameNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.PublicName = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) Description(val null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Description = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m userMods) DescriptionFunc(f func() null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Description = f
	})
}

// Clear any values for the column
func (m userMods) UnsetDescription() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Description = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomDescription(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Description = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomDescriptionNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Description = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) UserType(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UserType = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) UserTypeFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UserType = f
	})
}

// Clear any values for the column
func (m userMods) UnsetUserType() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UserType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomUserType(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UserType = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) Age(val int32) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Age = func() int32 { return val }
	})
}

// Set the Column from the function
func (m userMods) AgeFunc(f func() int32) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Age = f
	})
}

// Clear any values for the column
func (m userMods) UnsetAge() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Age = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomAge(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Age = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) InitialAge(val null.Val[int32]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.InitialAge = func() null.Val[int32] { return val }
	})
}

// Set the Column from the function
func (m userMods) InitialAgeFunc(f func() null.Val[int32]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.InitialAge = f
	})
}

// Clear any values for the column
func (m userMods) UnsetInitialAge() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.InitialAge = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomInitialAge(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.InitialAge = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomInitialAgeNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.InitialAge = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) Rate(val float64) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Rate = func() float64 { return val }
	})
}

// Set the Column from the function
func (m userMods) RateFunc(f func() float64) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Rate = f
	})
}

// Clear any values for the column
func (m userMods) UnsetRate() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Rate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomRate(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Rate = func() float64 {
			return random_float64(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) LastRate(val null.Val[float64]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LastRate = func() null.Val[float64] { return val }
	})
}

// Set the Column from the function
func (m userMods) LastRateFunc(f func() null.Val[float64]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LastRate = f
	})
}

// Clear any values for the column
func (m userMods) UnsetLastRate() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LastRate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomLastRate(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LastRate = func() null.Val[float64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_float64(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomLastRateNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LastRate = func() null.Val[float64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_float64(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) IsActive(val bool) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.IsActive = func() bool { return val }
	})
}

// Set the Column from the function
func (m userMods) IsActiveFunc(f func() bool) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.IsActive = f
	})
}

// Clear any values for the column
func (m userMods) UnsetIsActive() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.IsActive = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomIsActive(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.IsActive = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) ReadMessage(val null.Val[bool]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ReadMessage = func() null.Val[bool] { return val }
	})
}

// Set the Column from the function
func (m userMods) ReadMessageFunc(f func() null.Val[bool]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ReadMessage = f
	})
}

// Clear any values for the column
func (m userMods) UnsetReadMessage() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ReadMessage = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomReadMessage(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ReadMessage = func() null.Val[bool] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_bool(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomReadMessageNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ReadMessage = func() null.Val[bool] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_bool(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) Balance(val decimal.Decimal) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Balance = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m userMods) BalanceFunc(f func() decimal.Decimal) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Balance = f
	})
}

// Clear any values for the column
func (m userMods) UnsetBalance() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Balance = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomBalance(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Balance = func() decimal.Decimal {
			return random_decimal_Decimal(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) LockBalance(val null.Val[decimal.Decimal]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LockBalance = func() null.Val[decimal.Decimal] { return val }
	})
}

// Set the Column from the function
func (m userMods) LockBalanceFunc(f func() null.Val[decimal.Decimal]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LockBalance = f
	})
}

// Clear any values for the column
func (m userMods) UnsetLockBalance() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LockBalance = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomLockBalance(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LockBalance = func() null.Val[decimal.Decimal] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_decimal_Decimal(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomLockBalanceNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LockBalance = func() null.Val[decimal.Decimal] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_decimal_Decimal(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) LastLogin(val null.Val[time.Time]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LastLogin = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m userMods) LastLoginFunc(f func() null.Val[time.Time]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LastLogin = f
	})
}

// Clear any values for the column
func (m userMods) UnsetLastLogin() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LastLogin = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomLastLogin(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LastLogin = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomLastLoginNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.LastLogin = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) CreatedAt(val time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m userMods) CreatedAtFunc(f func() time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m userMods) UnsetCreatedAt() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomCreatedAt(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) UpdatedAt(val time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m userMods) UpdatedAtFunc(f func() time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m userMods) UnsetUpdatedAt() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomUpdatedAt(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m userMods) WithParentsCascading() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		if isDone, _ := userWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = userWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserTypeWithContext(ctx, UserTypeMods.WithParentsCascading())
			m.WithUserType(related).Apply(ctx, o)
		}
	})
}

func (m userMods) WithUserType(rel *UserTypeTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.UserType = &userRUserTypeR{
			o: rel,
		}
	})
}

func (m userMods) WithNewUserType(mods ...UserTypeMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewUserTypeWithContext(ctx, mods...)

		m.WithUserType(related).Apply(ctx, o)
	})
}

func (m userMods) WithExistingUserType(em *models.UserType) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.UserType = &userRUserTypeR{
			o: o.f.fromExistingUserType(ctx, em),
		}
	})
}

func (m userMods) WithoutUserType() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.UserType = nil
	})
}

func (m userMods) WithManagerCompanies(number int, related *CompanyTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ManagerCompanies = []*userRManagerCompaniesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewManagerCompanies(number int, mods ...CompanyMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewCompanyWithContext(ctx, mods...)
		m.WithManagerCompanies(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddManagerCompanies(number int, related *CompanyTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ManagerCompanies = append(o.r.ManagerCompanies, &userRManagerCompaniesR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewManagerCompanies(number int, mods ...CompanyMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewCompanyWithContext(ctx, mods...)
		m.AddManagerCompanies(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingManagerCompanies(existingModels ...*models.Company) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.ManagerCompanies = append(o.r.ManagerCompanies, &userRManagerCompaniesR{
				o: o.f.fromExistingCompany(ctx, em),
			})
		}
	})
}

func (m userMods) WithoutManagerCompanies() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ManagerCompanies = nil
	})
}

func (m userMods) WithOwnerCompanies(number int, related *CompanyTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.OwnerCompanies = []*userROwnerCompaniesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewOwnerCompanies(number int, mods ...CompanyMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewCompanyWithContext(ctx, mods...)
		m.WithOwnerCompanies(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddOwnerCompanies(number int, related *CompanyTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.OwnerCompanies = append(o.r.OwnerCompanies, &userROwnerCompaniesR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewOwnerCompanies(number int, mods ...CompanyMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewCompanyWithContext(ctx, mods...)
		m.AddOwnerCompanies(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingOwnerCompanies(existingModels ...*models.Company) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.OwnerCompanies = append(o.r.OwnerCompanies, &userROwnerCompaniesR{
				o: o.f.fromExistingCompany(ctx, em),
			})
		}
	})
}

func (m userMods) WithoutOwnerCompanies() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.OwnerCompanies = nil
	})
}
