// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	models "github.com/stepanbukhtii/go-blueprint/internal/repository/postgres/models"
	"github.com/stephenafamo/bob"
)

type UserTypeMod interface {
	Apply(context.Context, *UserTypeTemplate)
}

type UserTypeModFunc func(context.Context, *UserTypeTemplate)

func (f UserTypeModFunc) Apply(ctx context.Context, n *UserTypeTemplate) {
	f(ctx, n)
}

type UserTypeModSlice []UserTypeMod

func (mods UserTypeModSlice) Apply(ctx context.Context, n *UserTypeTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// UserTypeTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type UserTypeTemplate struct {
	Code    func() string
	Name    func() string
	IsAdmin func() bool

	r userTypeR
	f *Factory

	alreadyPersisted bool
}

type userTypeR struct {
	Users []*userTypeRUsersR
}

type userTypeRUsersR struct {
	number int
	o      *UserTemplate
}

// Apply mods to the UserTypeTemplate
func (o *UserTypeTemplate) Apply(ctx context.Context, mods ...UserTypeMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.UserType
// according to the relationships in the template. Nothing is inserted into the db
func (t UserTypeTemplate) setModelRels(o *models.UserType) {
	if t.r.Users != nil {
		rel := models.UserSlice{}
		for _, r := range t.r.Users {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UserType = o.Code // h2
				rel.R.UserType = o
				rel.R.Loaded.UserType = true
			}
			rel = append(rel, related...)
		}
		o.R.Users = rel
		o.R.Loaded.Users = true
	}
}

// BuildSetter returns an *models.UserTypeSetter
// this does nothing with the relationship templates
func (o UserTypeTemplate) BuildSetter() *models.UserTypeSetter {
	m := &models.UserTypeSetter{}

	if o.Code != nil {
		val := o.Code()
		m.Code = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.IsAdmin != nil {
		val := o.IsAdmin()
		m.IsAdmin = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.UserTypeSetter
// this does nothing with the relationship templates
func (o UserTypeTemplate) BuildManySetter(number int) []*models.UserTypeSetter {
	m := make([]*models.UserTypeSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.UserType
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserTypeTemplate.Create
func (o UserTypeTemplate) Build() *models.UserType {
	m := &models.UserType{}

	if o.Code != nil {
		m.Code = o.Code()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.IsAdmin != nil {
		m.IsAdmin = o.IsAdmin()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.UserTypeSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserTypeTemplate.CreateMany
func (o UserTypeTemplate) BuildMany(number int) models.UserTypeSlice {
	m := make(models.UserTypeSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableUserType(m *models.UserTypeSetter) {
	if !(m.Code.IsValue()) {
		val := random_string(nil)
		m.Code = omit.From(val)
	}
	if !(m.Name.IsValue()) {
		val := random_string(nil)
		m.Name = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.UserType
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *UserTypeTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.UserType) error {
	var err error

	isUsersDone, _ := userTypeRelUsersCtx.Value(ctx)
	if !isUsersDone && o.r.Users != nil {
		ctx = userTypeRelUsersCtx.WithValue(ctx, true)
		for _, r := range o.r.Users {
			if r.o.alreadyPersisted {
				m.R.Users = append(m.R.Users, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachUsers(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a userType and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *UserTypeTemplate) Create(ctx context.Context, exec bob.Executor) (*models.UserType, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableUserType(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	m, err := models.UserTypes.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}
	newMInCreation["user_type:users:users.users_user_type_fkey"] = m

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a userType and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *UserTypeTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.UserType {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a userType and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *UserTypeTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.UserType {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple userTypes and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o UserTypeTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.UserTypeSlice, error) {
	var err error
	m := make(models.UserTypeSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple userTypes and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o UserTypeTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.UserTypeSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple userTypes and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o UserTypeTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.UserTypeSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// UserType has methods that act as mods for the UserTypeTemplate
var UserTypeMods userTypeMods

type userTypeMods struct{}

func (m userTypeMods) RandomizeAllColumns(f *faker.Faker) UserTypeMod {
	return UserTypeModSlice{
		UserTypeMods.RandomCode(f),
		UserTypeMods.RandomName(f),
		UserTypeMods.RandomIsAdmin(f),
	}
}

// Set the model columns to this value
func (m userTypeMods) Code(val string) UserTypeMod {
	return UserTypeModFunc(func(_ context.Context, o *UserTypeTemplate) {
		o.Code = func() string { return val }
	})
}

// Set the Column from the function
func (m userTypeMods) CodeFunc(f func() string) UserTypeMod {
	return UserTypeModFunc(func(_ context.Context, o *UserTypeTemplate) {
		o.Code = f
	})
}

// Clear any values for the column
func (m userTypeMods) UnsetCode() UserTypeMod {
	return UserTypeModFunc(func(_ context.Context, o *UserTypeTemplate) {
		o.Code = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userTypeMods) RandomCode(f *faker.Faker) UserTypeMod {
	return UserTypeModFunc(func(_ context.Context, o *UserTypeTemplate) {
		o.Code = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userTypeMods) Name(val string) UserTypeMod {
	return UserTypeModFunc(func(_ context.Context, o *UserTypeTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m userTypeMods) NameFunc(f func() string) UserTypeMod {
	return UserTypeModFunc(func(_ context.Context, o *UserTypeTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m userTypeMods) UnsetName() UserTypeMod {
	return UserTypeModFunc(func(_ context.Context, o *UserTypeTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userTypeMods) RandomName(f *faker.Faker) UserTypeMod {
	return UserTypeModFunc(func(_ context.Context, o *UserTypeTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userTypeMods) IsAdmin(val bool) UserTypeMod {
	return UserTypeModFunc(func(_ context.Context, o *UserTypeTemplate) {
		o.IsAdmin = func() bool { return val }
	})
}

// Set the Column from the function
func (m userTypeMods) IsAdminFunc(f func() bool) UserTypeMod {
	return UserTypeModFunc(func(_ context.Context, o *UserTypeTemplate) {
		o.IsAdmin = f
	})
}

// Clear any values for the column
func (m userTypeMods) UnsetIsAdmin() UserTypeMod {
	return UserTypeModFunc(func(_ context.Context, o *UserTypeTemplate) {
		o.IsAdmin = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userTypeMods) RandomIsAdmin(f *faker.Faker) UserTypeMod {
	return UserTypeModFunc(func(_ context.Context, o *UserTypeTemplate) {
		o.IsAdmin = func() bool {
			return random_bool(f)
		}
	})
}

func (m userTypeMods) WithParentsCascading() UserTypeMod {
	return UserTypeModFunc(func(ctx context.Context, o *UserTypeTemplate) {
		if isDone, _ := userTypeWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = userTypeWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m userTypeMods) WithUsers(number int, related *UserTemplate) UserTypeMod {
	return UserTypeModFunc(func(ctx context.Context, o *UserTypeTemplate) {
		o.r.Users = []*userTypeRUsersR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userTypeMods) WithNewUsers(number int, mods ...UserMod) UserTypeMod {
	return UserTypeModFunc(func(ctx context.Context, o *UserTypeTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)
		m.WithUsers(number, related).Apply(ctx, o)
	})
}

func (m userTypeMods) AddUsers(number int, related *UserTemplate) UserTypeMod {
	return UserTypeModFunc(func(ctx context.Context, o *UserTypeTemplate) {
		o.r.Users = append(o.r.Users, &userTypeRUsersR{
			number: number,
			o:      related,
		})
	})
}

func (m userTypeMods) AddNewUsers(number int, mods ...UserMod) UserTypeMod {
	return UserTypeModFunc(func(ctx context.Context, o *UserTypeTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)
		m.AddUsers(number, related).Apply(ctx, o)
	})
}

func (m userTypeMods) AddExistingUsers(existingModels ...*models.User) UserTypeMod {
	return UserTypeModFunc(func(ctx context.Context, o *UserTypeTemplate) {
		for _, em := range existingModels {
			o.r.Users = append(o.r.Users, &userTypeRUsersR{
				o: o.f.fromExistingUser(ctx, em),
			})
		}
	})
}

func (m userTypeMods) WithoutUsers() UserTypeMod {
	return UserTypeModFunc(func(ctx context.Context, o *UserTypeTemplate) {
		o.r.Users = nil
	})
}
