// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Companies = Table[
	companyColumns,
	companyIndexes,
	companyForeignKeys,
	companyUniques,
	companyChecks,
]{
	Schema: "",
	Name:   "companies",
	Columns: companyColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "uuid_generate_v4()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		OwnerID: column{
			Name:      "owner_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ManagerID: column{
			Name:      "manager_id",
			DBType:    "uuid",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		IsActive: column{
			Name:      "is_active",
			DBType:    "boolean",
			Default:   "true",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		LogoURL: column{
			Name:      "logo_url",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp without time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp without time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: companyIndexes{
		CompaniesPkey: index{
			Type: "btree",
			Name: "companies_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "companies_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: companyForeignKeys{
		CompaniesCompaniesManagerIDFkey: foreignKey{
			constraint: constraint{
				Name:    "companies.companies_manager_id_fkey",
				Columns: []string{"manager_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
		CompaniesCompaniesOwnerIDFK: foreignKey{
			constraint: constraint{
				Name:    "companies.companies_owner_id_fk",
				Columns: []string{"owner_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type companyColumns struct {
	ID        column
	Name      column
	OwnerID   column
	ManagerID column
	IsActive  column
	LogoURL   column
	CreatedAt column
	UpdatedAt column
}

func (c companyColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.OwnerID, c.ManagerID, c.IsActive, c.LogoURL, c.CreatedAt, c.UpdatedAt,
	}
}

type companyIndexes struct {
	CompaniesPkey index
}

func (i companyIndexes) AsSlice() []index {
	return []index{
		i.CompaniesPkey,
	}
}

type companyForeignKeys struct {
	CompaniesCompaniesManagerIDFkey foreignKey
	CompaniesCompaniesOwnerIDFK     foreignKey
}

func (f companyForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.CompaniesCompaniesManagerIDFkey, f.CompaniesCompaniesOwnerIDFK,
	}
}

type companyUniques struct{}

func (u companyUniques) AsSlice() []constraint {
	return []constraint{}
}

type companyChecks struct{}

func (c companyChecks) AsSlice() []check {
	return []check{}
}
