// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Users = Table[
	userColumns,
	userIndexes,
	userForeignKeys,
	userUniques,
	userChecks,
]{
	Schema: "",
	Name:   "users",
	Columns: userColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "uuid_generate_v4()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Username: column{
			Name:      "username",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Password: column{
			Name:      "password",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PublicName: column{
			Name:      "public_name",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Description: column{
			Name:      "description",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UserType: column{
			Name:      "user_type",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Age: column{
			Name:      "age",
			DBType:    "integer",
			Default:   "1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InitialAge: column{
			Name:      "initial_age",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Rate: column{
			Name:      "rate",
			DBType:    "double precision",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		LastRate: column{
			Name:      "last_rate",
			DBType:    "double precision",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		IsActive: column{
			Name:      "is_active",
			DBType:    "boolean",
			Default:   "true",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ReadMessage: column{
			Name:      "read_message",
			DBType:    "boolean",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Balance: column{
			Name:      "balance",
			DBType:    "numeric",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		LockBalance: column{
			Name:      "lock_balance",
			DBType:    "numeric",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		LastLogin: column{
			Name:      "last_login",
			DBType:    "timestamp without time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp without time zone",
			Default:   "(now() AT TIME ZONE 'utc'::text)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp without time zone",
			Default:   "(now() AT TIME ZONE 'utc'::text)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: userIndexes{
		UsersPkey: index{
			Type: "btree",
			Name: "users_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UserUsernameUnique: index{
			Type: "btree",
			Name: "user_username_unique",
			Columns: []indexColumn{
				{
					Name:         "username",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UsersAgeIndex: index{
			Type: "btree",
			Name: "users_age_index",
			Columns: []indexColumn{
				{
					Name:         "age",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UsersNameBalanceIndex: index{
			Type: "btree",
			Name: "users_name_balance_index",
			Columns: []indexColumn{
				{
					Name:         "name",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "balance",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "users_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: userForeignKeys{
		UsersUsersUserTypeFkey: foreignKey{
			constraint: constraint{
				Name:    "users.users_user_type_fkey",
				Columns: []string{"user_type"},
				Comment: "",
			},
			ForeignTable:   "user_type",
			ForeignColumns: []string{"code"},
		},
	},
	Uniques: userUniques{
		UserUsernameUnique: constraint{
			Name:    "user_username_unique",
			Columns: []string{"username"},
			Comment: "",
		},
	},

	Comment: "",
}

type userColumns struct {
	ID          column
	Name        column
	Username    column
	Password    column
	PublicName  column
	Description column
	UserType    column
	Age         column
	InitialAge  column
	Rate        column
	LastRate    column
	IsActive    column
	ReadMessage column
	Balance     column
	LockBalance column
	LastLogin   column
	CreatedAt   column
	UpdatedAt   column
}

func (c userColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.Username, c.Password, c.PublicName, c.Description, c.UserType, c.Age, c.InitialAge, c.Rate, c.LastRate, c.IsActive, c.ReadMessage, c.Balance, c.LockBalance, c.LastLogin, c.CreatedAt, c.UpdatedAt,
	}
}

type userIndexes struct {
	UsersPkey             index
	UserUsernameUnique    index
	UsersAgeIndex         index
	UsersNameBalanceIndex index
}

func (i userIndexes) AsSlice() []index {
	return []index{
		i.UsersPkey, i.UserUsernameUnique, i.UsersAgeIndex, i.UsersNameBalanceIndex,
	}
}

type userForeignKeys struct {
	UsersUsersUserTypeFkey foreignKey
}

func (f userForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.UsersUsersUserTypeFkey,
	}
}

type userUniques struct {
	UserUsernameUnique constraint
}

func (u userUniques) AsSlice() []constraint {
	return []constraint{
		u.UserUsernameUnique,
	}
}

type userChecks struct{}

func (c userChecks) AsSlice() []check {
	return []check{}
}
