// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var UserTypes = Table[
	userTypeColumns,
	userTypeIndexes,
	userTypeForeignKeys,
	userTypeUniques,
	userTypeChecks,
]{
	Schema: "",
	Name:   "user_type",
	Columns: userTypeColumns{
		Code: column{
			Name:      "code",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsAdmin: column{
			Name:      "is_admin",
			DBType:    "boolean",
			Default:   "false",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: userTypeIndexes{
		UserTypePkey: index{
			Type: "btree",
			Name: "user_type_pkey",
			Columns: []indexColumn{
				{
					Name:         "code",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "user_type_pkey",
		Columns: []string{"code"},
		Comment: "",
	},

	Comment: "",
}

type userTypeColumns struct {
	Code    column
	Name    column
	IsAdmin column
}

func (c userTypeColumns) AsSlice() []column {
	return []column{
		c.Code, c.Name, c.IsAdmin,
	}
}

type userTypeIndexes struct {
	UserTypePkey index
}

func (i userTypeIndexes) AsSlice() []index {
	return []index{
		i.UserTypePkey,
	}
}

type userTypeForeignKeys struct{}

func (f userTypeForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type userTypeUniques struct{}

func (u userTypeUniques) AsSlice() []constraint {
	return []constraint{}
}

type userTypeChecks struct{}

func (c userTypeChecks) AsSlice() []check {
	return []check{}
}
